// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "Échec de la connexion",
    "requestFailed": "Échec de la requête",
    "unexpectedError": "Une erreur inattendue s'est produite",
    "sessionExpired": "Session expirée",
    "rateLimited": "Débit limité. Veuillez réessayer plus tard.",
    "networkError": "Erreur réseau. Veuillez vérifier votre connexion.",
    "failedToAddWorkspace": "Échec de l'ajout de l'espace de travail.",
    "failedToOpenNewWindow": "Échec de l'ouverture d'une nouvelle fenêtre.",
    "failedToCreateSession": "Échec de la création de la session.",
    "failedToCreateSessionNoThreadId": "Le runtime n'a pas renvoyé de nouvel identifiant de session.",
    "failedToCreateSessionRuntimeRecovering": "Le runtime redémarrait lors de la création de cette session. L'application a déjà réessayé une fois. Reconnectez l'espace de travail et réessayez.",
    "codexProviderWireApiUnsupported": "La version actuelle de Codex CLI ne prend pas en charge wire_api = \"chat\". Si ce fournisseur prend en charge Responses API, utilisez wire_api = \"responses\". S'il ne prend en charge que Chat Completions, configurez d'abord un service de conversion de protocole ou un router.",
    "reconnectAndRetryCreateSession": "Reconnecter et réessayer la création",
    "reconnectingAndRetryingCreateSession": "Reconnexion et nouvelle tentative de création...",
    "runtimeRecovered": "Runtime récupéré.",
    "retryingCreateSessionAfterRecovery": "Nouvelle tentative de création de session...",
    "cliNotFound": "Ni la CLI Claude Code ni la CLI Codex n'ont été trouvées. Veuillez en installer une.",
    "cliNotFoundHint": "Installer Claude Code : curl -fsSL https://claude.ai/install.sh | bash\nInstaller Codex : npm install -g @openai/codex",
    "codexCliNotFound": "CLI Codex introuvable. Installez Codex et assurez-vous que `codex` est dans votre PATH.",
    "couldntOpenWorkspace": "Impossible d'ouvrir l'espace de travail",
    "dismissError": "Ignorer l'erreur"
  }
};

export default errors;
