// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "連線失敗",
    "requestFailed": "請求失敗",
    "unexpectedError": "發生非預期的錯誤",
    "sessionExpired": "工作階段已過期",
    "rateLimited": "已達速率限制。請稍後再試。",
    "networkError": "網路錯誤。請檢查你的連線。",
    "failedToAddWorkspace": "無法新增工作區。",
    "failedToOpenNewWindow": "無法開啟新視窗。",
    "failedToCreateSession": "無法建立工作階段。",
    "failedToCreateSessionNoThreadId": "執行環境未傳回新的工作階段 id。",
    "failedToCreateSessionRuntimeRecovering": "建立此工作階段時執行環境正在重新啟動。應用程式已自動重試一次。請重新連線工作區後再試一次。",
    "codexProviderWireApiUnsupported": "目前 Codex CLI 不支援 wire_api = \"chat\"。如果此供應商支援 Responses API，請改用 wire_api = \"responses\"；如果僅支援 Chat Completions，請先設定協議轉換服務或 router。",
    "codexProviderConfigInvalid": "此 Codex 供應商設定不是有效的 TOML。請檢查語法，並使用英文半形直引號 (\")，不要使用彎引號。",
    "reconnectAndRetryCreateSession": "重新連線並重試建立",
    "reconnectingAndRetryingCreateSession": "正在重新連線並重試建立…",
    "runtimeRecovered": "執行環境已復原。",
    "retryingCreateSessionAfterRecovery": "正在重試建立工作階段…",
    "cliNotFound": "找不到 Claude Code CLI 或 Codex CLI。請安裝其中之一。",
    "cliNotFoundHint": "安裝 Claude Code：curl -fsSL https://claude.ai/install.sh | bash\n安裝 Codex：npm install -g @openai/codex",
    "codexCliNotFound": "找不到 Codex CLI。請安裝 Codex 並確認 `codex` 已加入你的 PATH。",
    "couldntOpenWorkspace": "無法開啟工作區",
    "dismissError": "關閉錯誤",
    "applicationErrorTitle": "應用錯誤",
    "applicationErrorDescription": "介面因意外錯誤無法繼續顯示。請先複製下方診斷資訊回饋給開發者，再嘗試重新載入應用。",
    "applicationErrorReload": "重新載入",
    "applicationErrorCopyReport": "一鍵複製診斷資訊",
    "applicationErrorCopyDone": "診斷資訊已複製，請貼到回饋裡發給開發者。",
    "applicationErrorCopyDownloaded": "目前環境無法寫入剪貼簿，已改為下載診斷檔。回饋時請附上該檔案。",
    "applicationErrorCopyFailed": "複製與下載都失敗了。請手動選取下方文字複製後回饋。",
    "applicationErrorDetails": "錯誤詳情",
    "applicationErrorFeedbackTitle": "如何回饋給開發者",
    "applicationErrorFeedbackStep1": "點擊「一鍵複製診斷資訊」。",
    "applicationErrorFeedbackStep2": "開啟回饋頁新建 Issue，把診斷資訊貼進去。",
    "applicationErrorFeedbackStep3": "補充你當時在做什麼（冷啟動 / 串流輸出 / 切換工作區等），以及重新載入是否恢復。",
    "applicationErrorOpenFeedback": "開啟回饋頁面",
    "applicationErrorMeta": "版本: {{version}} · 類型: {{errorClass}} · 平台: {{platform}}",
    "applicationErrorMessageLabel": "錯誤訊息",
    "applicationErrorDecodedLabel": "React #{{code}} 完整含義",
    "applicationErrorComponentStackLabel": "元件堆疊",
    "applicationErrorStackLabel": "JavaScript 堆疊"
  }
};

export default errors;
