import { useEffect, useRef } from "react";
import { APP_SHELL_LEGACY_CONTEXT_DEFAULTS } from "../legacy/legacyContextDefaults";
import {
  buildCollaborationModeDomainContextSlice,
  buildModelSelectionDomainContextSlice,
  buildRuntimeDomainContextSlice,
  buildRuntimeThreadDomainContextSlice,
  buildSessionIdentityDomainContextSlice,
  buildWorkspaceCatalogDomainContextSlice,
  buildGitSurfaceDomainContextSlice,
  buildModeRoutingDomainContextSlice,
  buildAccountSurfaceDomainContextSlice,
  buildDictationSurfaceDomainContextSlice,
  buildWorkspaceNavigationDomainContextSlice,
} from "./buildAppShellDomainContextSlices";
import {
  defineAppShellDomainContexts,
  reuseStableAppShellDomainContexts,
  type AppShellDomainContextValue,
  type AppShellDomainContexts,
} from "./appShellDomainContexts";

/**
 * T1.1：AppShell domain bag assembly。
 *
 * 将 `defineAppShellDomainContexts` 字面量与 `reuseStable*` 从 `app-shell.tsx` 下沉到此模块。
 * 根组件只传入已解析源值（property shorthand），不再内联 domain bag。
 *
 * 输入类型刻意放宽：输出键所有权仍由 `defineAppShellDomainContexts` + owner map 测试锁定。
 */
export type AppShellDomainAssemblySource = Record<string, unknown>;

export function assembleAppShellDomainContexts(
  source: AppShellDomainAssemblySource,
): AppShellDomainContexts {
  return defineAppShellDomainContexts(
{
    runtimeThreadContext: buildRuntimeThreadDomainContextSlice({
      legacyDefaults: APP_SHELL_LEGACY_CONTEXT_DEFAULTS,
      runtimeActions: source.runtimeActions as AppShellDomainContextValue,
      runtimeThreadBoundary: source.runtimeThreadBoundary,
      // S4 PR-D：turn 级 conversation bags 归 conversation 域（runtimeThreadContext）。
      // 读侧仅 layoutNodes（订阅全 15 域）；sections/render 不订阅本域，
      // 其所需 threadsByWorkspace / threadStatusById 等仍留 settingsContext。
      historyLoadingByThreadId: source.historyLoadingByThreadId,
      historyLoadingProgressByThreadId: source.historyLoadingProgressByThreadId,
      historyRestoredAtMsByThread: source.historyRestoredAtMsByThread,
      threadListCursorByWorkspace: source.threadListCursorByWorkspace,
      threadListPagingByWorkspace: source.threadListPagingByWorkspace,
      threadParentById: source.threadParentById,
      // S4 PR-C：conversation UI 与 review-prompt 流程（读侧仅 layoutNodes）
      handleCopyThread: source.handleCopyThread,
      handleDeleteThreadPromptCancel: source.handleDeleteThreadPromptCancel,
      handleDeleteThreadPromptConfirm: source.handleDeleteThreadPromptConfirm,
      handleRenamePromptCancel: source.handleRenamePromptCancel,
      handleRenamePromptChange: source.handleRenamePromptChange,
      handleRenamePromptConfirm: source.handleRenamePromptConfirm,
      handleRenameThread: source.handleRenameThread,
      hydratedThreadListWorkspaceIds: source.hydratedThreadListWorkspaceIds,
      isDeleteThreadPromptBusy: source.isDeleteThreadPromptBusy,
      choosePreset: source.choosePreset,
      handleReviewPromptKeyDown: source.handleReviewPromptKeyDown,
      handleSelectCommit: source.handleSelectCommit,
      handleSelectStatusPanelSubagent: source.handleSelectStatusPanelSubagent,
      highlightedBranchIndex: source.highlightedBranchIndex,
      highlightedCommitIndex: source.highlightedCommitIndex,
      highlightedPresetIndex: source.highlightedPresetIndex,
      // 高 churn 会话投影：独立 domain，避免打坏 workspaceNavigation shallow equal
      sessionHot: {
        activeItems: source.activeItems,
        activePlan: source.activePlan,
        activeRateLimits: source.activeRateLimits,
        activeTokenUsage: source.activeTokenUsage,
        activeTurnId: source.activeTurnId,
        canInterrupt: source.canInterrupt,
        isProcessing: source.isProcessing,
        isReviewing: source.isReviewing,
        timelinePlan: source.timelinePlan,
      },
    }),
    sessionIdentityContext: buildSessionIdentityDomainContextSlice({
      RECENT_THREAD_LIMIT: source.RECENT_THREAD_LIMIT,
      activeParentWorkspace: source.activeParentWorkspace,
      activePath: source.activePath,
      activeThreadId: source.activeThreadId,
      activeThreadIdForModeRef: source.activeThreadIdForModeRef,
      activeThreadIdRef: source.activeThreadIdRef,
      activeWorkspace: source.activeWorkspace,
      activeWorkspaceId: source.activeWorkspaceId,
      activeWorkspaceIdRef: source.activeWorkspaceIdRef,
      activeWorkspaceRef: source.activeWorkspaceRef,
      activeWorkspaceThreads: source.activeWorkspaceThreads,
      baseWorkspaceRef: source.baseWorkspaceRef,
    }),
    workspaceCatalogContext: buildWorkspaceCatalogDomainContextSlice({
      addCloneAgent: source.addCloneAgent,
      addWorkspace: source.addWorkspace,
      addWorkspaceFromPath: source.addWorkspaceFromPath,
      addWorktreeAgent: source.addWorktreeAgent,
      assignWorkspaceGroup: source.assignWorkspaceGroup,
      cancelClonePrompt: source.cancelClonePrompt,
      cancelWorktreePrompt: source.cancelWorktreePrompt,
      chooseCloneCopiesFolder: source.chooseCloneCopiesFolder,
      clearCloneCopiesFolder: source.clearCloneCopiesFolder,
      clonePrompt: source.clonePrompt,
      closeWorktreeCreateResult: source.closeWorktreeCreateResult,
      confirmClonePrompt: source.confirmClonePrompt,
      confirmRenameWorktreeUpstream: source.confirmRenameWorktreeUpstream,
      confirmWorktreePrompt: source.confirmWorktreePrompt,
      connectWorkspace: source.connectWorkspace,
      createWorkspaceGroup: source.createWorkspaceGroup,
      deleteWorkspaceGroup: source.deleteWorkspaceGroup,
      deletingWorktreeIds: source.deletingWorktreeIds,
      directories: source.directories,
      directoryMetadata: source.directoryMetadata,
      ensureWorkspaceThreadListLoaded: source.ensureWorkspaceThreadListLoaded,
      forkThreadForWorkspace: source.forkThreadForWorkspace,
      forkSessionFromMessageForWorkspace: source.forkSessionFromMessageForWorkspace,
      forkClaudeSessionFromMessageForWorkspace: source.forkClaudeSessionFromMessageForWorkspace,
      getWorkspaceGroupName: source.getWorkspaceGroupName,
      getWorkspacePromptsDir: source.getWorkspacePromptsDir,
      repositories: source.repositories,
      repositoriesLoading: source.repositoriesLoading,
      isMultiRepository: source.isMultiRepository,
      // S4 PR-C：workspace/agent 入口与拖放 intake（从 composerContext 归位）
      groupedWorkspaces: source.groupedWorkspaces,
      handleAddAgent: source.handleAddAgent,
      handleAddCloneAgent: source.handleAddCloneAgent,
      handleAddWorkspace: source.handleAddWorkspace,
      handleAddWorktreeAgent: source.handleAddWorktreeAgent,
      handleArchiveActiveThread: source.handleArchiveActiveThread,
      handleEnsureWorkspaceThreadsForSettings:
        source.handleEnsureWorkspaceThreadsForSettings,
      handleOpenNewWindow: source.handleOpenNewWindow,
      handleWorkspaceDragEnter: source.handleWorkspaceDragEnter,
      handleWorkspaceDragLeave: source.handleWorkspaceDragLeave,
      handleWorkspaceDragOver: source.handleWorkspaceDragOver,
      handleWorkspaceDrop: source.handleWorkspaceDrop,
    }),
    gitSurfaceContext: buildGitSurfaceDomainContextSlice({
      GitHubPanelData: source.GitHubPanelData,
      activeDiffError: source.activeDiffError,
      activeDiffLoading: source.activeDiffLoading,
      activeDiffs: source.activeDiffs,
      activeGitRoot: source.activeGitRoot,
      activeGitHistoryTabId: source.activeGitHistoryTabId,
      branchError: source.branchError,
      branches: source.branches,
      checkoutBranch: source.checkoutBranch,
      clearGitOperationErrors: source.clearGitOperationErrors,
      clearGitRootCandidates: source.clearGitRootCandidates,
      commitError: source.commitError,
      commitLoading: source.commitLoading,
      commitMessage: source.commitMessage,
      commitMessageError: source.commitMessageError,
      commitMessageLoading: source.commitMessageLoading,
      confirmBranch: source.confirmBranch,
      confirmCommit: source.confirmCommit,
      createBranch: source.createBranch,
      currentBranch: source.currentBranch,
      diffScrollRequestId: source.diffScrollRequestId,
      diffSource: source.diffSource,
      exitDiffView: source.exitDiffView,
      fileStatus: source.fileStatus,
      gitCommitDiffs: source.gitCommitDiffs,
      gitDiffListView: source.gitDiffListView,
      gitDiffViewStyle: source.gitDiffViewStyle,
      gitHistoryPanelHeight: source.gitHistoryPanelHeight,
      gitHistoryPanelHeightRef: source.gitHistoryPanelHeightRef,
      gitIssues: source.gitIssues,
      gitIssuesError: source.gitIssuesError,
      gitIssuesLoading: source.gitIssuesLoading,
      gitIssuesTotal: source.gitIssuesTotal,
      gitLogAhead: source.gitLogAhead,
      gitLogAheadEntries: source.gitLogAheadEntries,
      gitLogBehind: source.gitLogBehind,
      gitLogBehindEntries: source.gitLogBehindEntries,
      gitLogEntries: source.gitLogEntries,
      gitLogError: source.gitLogError,
      gitLogLoading: source.gitLogLoading,
      gitLogTotal: source.gitLogTotal,
      gitLogUpstream: source.gitLogUpstream,
      gitPanelMode: source.gitPanelMode,
      gitPullRequestComments: source.gitPullRequestComments,
      gitPullRequestCommentsError: source.gitPullRequestCommentsError,
      gitPullRequestCommentsLoading: source.gitPullRequestCommentsLoading,
      gitPullRequestDiffs: source.gitPullRequestDiffs,
      gitPullRequestDiffsError: source.gitPullRequestDiffsError,
      gitPullRequestDiffsLoading: source.gitPullRequestDiffsLoading,
      gitPullRequests: source.gitPullRequests,
      gitPullRequestsError: source.gitPullRequestsError,
      gitPullRequestsLoading: source.gitPullRequestsLoading,
      gitPullRequestsTotal: source.gitPullRequestsTotal,
      gitRemoteUrl: source.gitRemoteUrl,
      gitRootCandidates: source.gitRootCandidates,
      gitRootScanDepth: source.gitRootScanDepth,
      gitRootScanError: source.gitRootScanError,
      gitRootScanHasScanned: source.gitRootScanHasScanned,
      gitRootScanLoading: source.gitRootScanLoading,
      gitStatus: source.gitStatus,
      gitignoredDirectories: source.gitignoredDirectories,
      gitignoredFiles: source.gitignoredFiles,
      localBranches: source.localBranches,
      remoteBranches: source.remoteBranches,
      repositoryError: source.repositoryError,
      repositoryStatuses: source.repositoryStatuses,
      repositoryStatusesLoading: source.repositoryStatusesLoading,
      refreshRepositoryStatuses: source.refreshRepositoryStatuses,
      handleStageRepositoryFile: source.handleStageRepositoryFile,
      handleUnstageRepositoryFile: source.handleUnstageRepositoryFile,
      handleUnstageRepositoryAll: source.handleUnstageRepositoryAll,
      handleUnstageRepositoryFiles: source.handleUnstageRepositoryFiles,
      handleRevertRepositoryFile: source.handleRevertRepositoryFile,
      handleRevertRepositoryFiles: source.handleRevertRepositoryFiles,
      handleStageRepositoryAll: source.handleStageRepositoryAll,
      handleCommitRepositories: source.handleCommitRepositories,
      repositoryCommitSummary: source.repositoryCommitSummary,
      selectRepository: source.selectRepository,
      selectedRepositoryRoot: source.selectedRepositoryRoot,
      // S4 PR-C：git 操作 handlers 从 composerContext 归位
      handleActivateGitHistoryTab: source.handleActivateGitHistoryTab,
      handleActiveDiffPath: source.handleActiveDiffPath,
      handleApplyWorktreeChanges: source.handleApplyWorktreeChanges,
      handleCheckoutBranch: source.handleCheckoutBranch,
      handleCommit: source.handleCommit,
      handleCommitAndPush: source.handleCommitAndPush,
      handleCommitAndSync: source.handleCommitAndSync,
      handleCommitMessageChange: source.handleCommitMessageChange,
      handleCreateBranch: source.handleCreateBranch,
      handleGenerateCommitMessage: source.handleGenerateCommitMessage,
      handleGitIssuesChange: source.handleGitIssuesChange,
      handleGitPanelModeChange: source.handleGitPanelModeChange,
      handleGitPullRequestCommentsChange:
        source.handleGitPullRequestCommentsChange,
      handleGitPullRequestDiffsChange: source.handleGitPullRequestDiffsChange,
      handleGitPullRequestsChange: source.handleGitPullRequestsChange,
      handlePickGitRoot: source.handlePickGitRoot,
      handlePush: source.handlePush,
      handleRevertAllGitChanges: source.handleRevertAllGitChanges,
      handleRevertGitFile: source.handleRevertGitFile,
      handleRevertGitPaths: source.handleRevertGitPaths,
      handleSetGitRoot: source.handleSetGitRoot,
      handleStageGitAll: source.handleStageGitAll,
      handleStageGitFile: source.handleStageGitFile,
      handleSync: source.handleSync,
      handleUnstageGitAll: source.handleUnstageGitAll,
      handleUnstageGitFile: source.handleUnstageGitFile,
      handleUnstageGitPaths: source.handleUnstageGitPaths,
      handleUpdateBranch: source.handleUpdateBranch,
      handleUpdateAllRepositories: source.handleUpdateAllRepositories,
      handleCheckoutAllRepositories: source.handleCheckoutAllRepositories,
      handleLoadCommonRepositoryBranches:
        source.handleLoadCommonRepositoryBranches,
    }),
    modeRoutingContext: buildModeRoutingDomainContextSlice({
      accessMode: source.accessMode,
      activeTab: source.activeTab,
      appMode: source.appMode,
      centerMode: source.centerMode,
      claudeAccessModeRef: source.claudeAccessModeRef,
      filePanelMode: source.filePanelMode,
      // S4 PR-C：UI 模式/面板路由与环境标志（从 composerContext 归位）
      handleAppModeChange: source.handleAppModeChange,
      handleDebugClick: source.handleDebugClick,
      handleLockPanel: source.handleLockPanel,
      handleResolvedClaudeThinkingVisibleChange:
        source.handleResolvedClaudeThinkingVisibleChange,
      handleToggleRuntimeConsole: source.handleToggleRuntimeConsole,
      handleToggleTerminalPanel: source.handleToggleTerminalPanel,
      handleUnlockPanel: source.handleUnlockPanel,
      hasActivePlan: source.hasActivePlan,
      isCompact: source.isCompact,
      isMacDesktop: source.isMacDesktop,
      isPanelLocked: source.isPanelLocked,
      isPhone: source.isPhone,
      isSearchPaletteOpen: source.isSearchPaletteOpen,
    }),
    accountSurfaceContext: buildAccountSurfaceDomainContextSlice({
      accountByWorkspace: source.accountByWorkspace,
      accountSwitching: source.accountSwitching,
      activeAccount: source.activeAccount,
      approvals: source.approvals,
      // S4 PR-C：账号切换 / 审批 / 邮件会话入口（从 composerContext 归位）
      handleApprovalBatchAccept: source.handleApprovalBatchAccept,
      handleApprovalDecision: source.handleApprovalDecision,
      handleApprovalRemember: source.handleApprovalRemember,
      handleCancelSwitchAccount: source.handleCancelSwitchAccount,
      handleOpenMailSession: source.handleOpenMailSession,
      handleSwitchAccount: source.handleSwitchAccount,
    }),
    dictationSurfaceContext: buildDictationSurfaceDomainContextSlice({
      clearDictationError: source.clearDictationError,
      clearDictationHint: source.clearDictationHint,
      clearDictationTranscript: source.clearDictationTranscript,
      dictationError: source.dictationError,
      dictationHint: source.dictationHint,
      dictationLevel: source.dictationLevel,
      dictationModel: source.dictationModel,
      dictationReady: source.dictationReady,
      dictationState: source.dictationState,
      dictationTranscript: source.dictationTranscript,
      // S4 PR-C：听写开关（从 composerContext 归位）
      handleToggleDictation: source.handleToggleDictation,
    }),
    workspaceNavigationContext: buildWorkspaceNavigationDomainContextSlice({
      SettingsView: source.SettingsView,
      activeEditorFilePath: source.activeEditorFilePath,
      activeEditorLineRange: source.activeEditorLineRange,
      activeEngine: source.activeEngine,
      fileCompareSession: source.fileCompareSession,
      fileHistoryTabs: source.fileHistoryTabs,
      activeRenamePrompt: source.activeRenamePrompt,
      agentTaskScrollRequest: source.agentTaskScrollRequest,
      activeTerminalId: source.activeTerminalId,
      activeWorkspaceKanbanTasks: source.activeWorkspaceKanbanTasks,
      addDebugEntry: source.addDebugEntry,
      agent: source.agent,
      alertError: source.alertError,
      appRootRef: source.appRootRef,
      appSettings: source.appSettings,
      appSettingsLoading: source.appSettingsLoading,
      claudeThinkingVisible: source.claudeThinkingVisible,
      clearDebugEntries: source.clearDebugEntries,
      clearDraftForThread: source.clearDraftForThread,
      closePlanPanel: source.closePlanPanel,
      checkForUpdates: source.checkForUpdates,
      closeReleaseNotes: source.closeReleaseNotes,
      closeReviewPrompt: source.closeReviewPrompt,
      closeSettings: source.closeSettings,
      closeTerminalPanel: source.closeTerminalPanel,
      collapseRightPanel: source.collapseRightPanel,
      collapseSidebar: source.collapseSidebar,
      commands: source.commands,
      completionEmailIntentByThread: source.completionEmailIntentByThread,
      completionTrackerBySessionRef: source.completionTrackerBySessionRef,
      completionTrackerReadyRef: source.completionTrackerReadyRef,
      confirmCustom: source.confirmCustom,
      createPrompt: source.createPrompt,
      debugEntries: source.debugEntries,
      debugOpen: source.debugOpen,
      debugPanelHeight: source.debugPanelHeight,
      deletePrompt: source.deletePrompt,
      deleteThreadPrompt: source.deleteThreadPrompt,
      dismissErrorToast: source.dismissErrorToast,
      dismissUpdate: source.dismissUpdate,
      doctor: source.doctor,
      claudeDoctor: source.claudeDoctor,
      kimiDoctor: source.kimiDoctor,
      grokDoctor: source.grokDoctor,
      opencodeDoctor: source.opencodeDoctor,
      editorHighlightTarget: source.editorHighlightTarget,
      editorNavigationTarget: source.editorNavigationTarget,
      editorSplitCompanion: source.editorSplitCompanion,
      editorSplitLayout: source.editorSplitLayout,
      engineModelsAsOptions: source.engineModelsAsOptions,
      engineSelectedModelIdByType: source.engineSelectedModelIdByType,
      engineStatuses: source.engineStatuses,
      ensureLaunchTerminal: source.ensureLaunchTerminal,
      ensureTerminalWithTitle: source.ensureTerminalWithTitle,
      errorToasts: source.errorToasts,
      expandRightPanel: source.expandRightPanel,
      expandSidebar: source.expandSidebar,
      fileReferenceMode: source.fileReferenceMode,
      fileTreeLoadError: source.fileTreeLoadError,
      fileTreeSourceVersion: source.fileTreeSourceVersion,
      files: source.files,
      getGlobalPromptsDir: source.getGlobalPromptsDir,
      getPinTimestamp: source.getPinTimestamp,
      getThreadRows: source.getThreadRows,
      globalSearchFilesByWorkspace: source.globalSearchFilesByWorkspace,
      // S4 PR-C：debug/updater 动作（从 composerContext 归位）
      handleCopyDebug: source.handleCopyDebug,
      handleTestNotificationSound: source.handleTestNotificationSound,
    }),
    composerContext: {
      // S4 PR-C：composer 输入面（draft/queue/images/prefill/insert + 发送/队列
      // handlers + prompts 库 + agent/access-mode 选择 + interruptTurn）。
      // 原 141 把钥匙中无 bag 读者的已删除，其余按语义归位到
      // gitSurface / fileEditor / modeRouting / accountSurface / dictationSurface /
      // workspaceCatalog / workspaceNavigation / runtimeThread / modelSelection。
      activeFusingMessageId: source.activeFusingMessageId,
      activeImages: source.activeImages,
      activeQueue: source.activeQueue,
      activeQueuedHandoffBubble: source.activeQueuedHandoffBubble,
      attachImages: source.attachImages,
      canFuseActiveQueue: source.canFuseActiveQueue,
      composerEditorSettings: source.composerEditorSettings,
      composerInputRef: source.composerInputRef,
      composerInsert: source.composerInsert,
      fuseDisabledReasonKey: source.fuseDisabledReasonKey,
      handleCreatePrompt: source.handleCreatePrompt,
      handleDeletePrompt: source.handleDeletePrompt,
      handleDeleteQueued: source.handleDeleteQueued,
      handleDraftChange: source.handleDraftChange,
      handleEditQueued: source.handleEditQueued,
      handleExitPlanModeExecute: source.handleExitPlanModeExecute,
      handleFuseQueued: source.handleFuseQueued,
      handleInsertComposerText: source.handleInsertComposerText,
      handleMovePrompt: source.handleMovePrompt,
      handleRevealGeneralPrompts: source.handleRevealGeneralPrompts,
      handleRevealWorkspacePrompts: source.handleRevealWorkspacePrompts,
      handleSelectAgent: source.handleSelectAgent,
      handleSendPrompt: source.handleSendPrompt,
      handleSendPromptToNewAgent: source.handleSendPromptToNewAgent,
      handleSetAccessMode: source.handleSetAccessMode,
      handleUpdatePrompt: source.handleUpdatePrompt,
      handleUserInputSubmit: source.handleUserInputSubmit,
      handleUserInputSubmitWithPlanApply:
        source.handleUserInputSubmitWithPlanApply,
      interruptTurn: source.interruptTurn,
      isPlanMode: source.isPlanMode,
      isPlanPanelDismissed: source.isPlanPanelDismissed,
      onTextareaHeightChange: source.onTextareaHeightChange,
      pickImages: source.pickImages,
      prefillDraft: source.prefillDraft,
      removeImage: source.removeImage,
      setComposerInsert: source.setComposerInsert,
      setPrefillDraft: source.setPrefillDraft,
      skills: source.skills,
      textareaHeight: source.textareaHeight,
    },
    layoutContext: {
      isTablet: source.isTablet,
      isThreadAutoNaming: source.isThreadAutoNaming,
      isThreadPinned: source.isThreadPinned,
      isWindowsDesktop: source.isWindowsDesktop,
      isWorkspaceDropActive: source.isWorkspaceDropActive,
      isWorktreeWorkspace: source.isWorktreeWorkspace,
      kanbanConversationWidth: source.kanbanConversationWidth,
      kanbanCreatePanel: source.kanbanCreatePanel,
      kanbanCreateTask: source.kanbanCreateTask,
      kanbanDeletePanel: source.kanbanDeletePanel,
      kanbanDeleteTask: source.kanbanDeleteTask,
      kanbanPanels: source.kanbanPanels,
      kanbanReorderTask: source.kanbanReorderTask,
      kanbanTasks: source.kanbanTasks,
      kanbanUpdatePanel: source.kanbanUpdatePanel,
      kanbanUpdateTask: source.kanbanUpdateTask,
      kanbanViewState: source.kanbanViewState,
      lastCodexModeSyncThreadRef: source.lastCodexModeSyncThreadRef,
      launchScriptState: source.launchScriptState,
      launchScriptsState: source.launchScriptsState,
      listThreadsForWorkspace: source.listThreadsForWorkspace,
      listThreadsForWorkspaceTracked: source.listThreadsForWorkspaceTracked,
      liveEditPreviewEnabled: source.liveEditPreviewEnabled,
      loadOlderThreadsForWorkspace: source.loadOlderThreadsForWorkspace,
      lockLiveSessions: source.lockLiveSessions,
      markWorkspaceConnected: source.markWorkspaceConnected,
      models: source.models,
      movePrompt: source.movePrompt,
      moveWorkspaceGroup: source.moveWorkspaceGroup,
      navigateToThread: source.navigateToThread,
      handleOpenClaudeTui: source.handleOpenClaudeTui,
      normalizePath: source.normalizePath,
      onCloseTerminal: source.onCloseTerminal,
      onDebugPanelResizeStart: source.onDebugPanelResizeStart,
      onGitHistoryPanelResizeStart: source.onGitHistoryPanelResizeStart,
      onKanbanConversationResizeStart: source.onKanbanConversationResizeStart,
      onNewTerminal: source.onNewTerminal,
      onPlanPanelResizeStart: source.onPlanPanelResizeStart,
      onRightPanelResizeStart: source.onRightPanelResizeStart,
      onSelectTerminal: source.onSelectTerminal,
      onSidebarResizeStart: source.onSidebarResizeStart,
      onTerminalPanelResizeStart: source.onTerminalPanelResizeStart,
      openAppIconById: source.openAppIconById,
      openClonePrompt: source.openClonePrompt,
      openCodeAgents: source.openCodeAgents,
      openDeleteThreadPrompt: source.openDeleteThreadPrompt,
      openFileTabs: source.openFileTabs,
      openPlanPanel: source.openPlanPanel,
      openReleaseNotes: source.openReleaseNotes,
      openRenamePrompt: source.openRenamePrompt,
      openRenameWorktreePrompt: source.openRenameWorktreePrompt,
      openSettings: source.openSettings,
      openTerminal: source.openTerminal,
      openWorktreePrompt: source.openWorktreePrompt,
      perfSnapshotRef: source.perfSnapshotRef,
      persistComposerSelectionForThread: source.persistComposerSelectionForThread,
      persistProjectCopiesFolder: source.persistProjectCopiesFolder,
      pinThread: source.pinThread,
      pinnedThreadsVersion: source.pinnedThreadsVersion,
      planPanelHeight: source.planPanelHeight,
      prompts: source.prompts,
      pushError: source.pushError,
      pushLoading: source.pushLoading,
      queueGitStatusRefresh: source.queueGitStatusRefresh,
      queueSaveSettings: source.queueSaveSettings,
      recentThreads: source.recentThreads,
      reduceTransparency: source.reduceTransparency,
      windowTransparencyEnabled: source.windowTransparencyEnabled,
      windowOpacity: source.windowOpacity,
      refreshAccountInfo: source.refreshAccountInfo,
      refreshAccountRateLimits: source.refreshAccountRateLimits,
      refreshEngines: source.refreshEngines,
      refreshFiles: source.refreshFiles,
      refreshGitDiffs: source.refreshGitDiffs,
      refreshGitLog: source.refreshGitLog,
      refreshGitStatus: source.refreshGitStatus,
      refreshThread: source.refreshThread,
      refreshWorkspaces: source.refreshWorkspaces,
      releaseNotesActiveIndex: source.releaseNotesActiveIndex,
      releaseNotesEntries: source.releaseNotesEntries,
      releaseNotesError: source.releaseNotesError,
      releaseNotesLoading: source.releaseNotesLoading,
      releaseNotesOpen: source.releaseNotesOpen,
      reloadSelectedAgent: source.reloadSelectedAgent,
      removeImagesForThread: source.removeImagesForThread,
      removeThread: source.removeThread,
      removeThreads: source.removeThreads,
      removeWorkspace: source.removeWorkspace,
      removeWorktree: source.removeWorktree,
      renamePrompt: source.renamePrompt,
      renameThread: source.renameThread,
      renameWorkspaceGroup: source.renameWorkspaceGroup,
      renameWorktree: source.renameWorktree,
      renameWorktreeNotice: source.renameWorktreeNotice,
      renameWorktreePrompt: source.renameWorktreePrompt,
    },
    fileEditorContext: {
      // S4 PR-C：文件 tab / editor / compare / file-history 动作（从 composerContext 归位）
      handleActivateFileTab: source.handleActivateFileTab,
      handleCloseAllFileHistories: source.handleCloseAllFileHistories,
      handleCloseAllFileTabs: source.handleCloseAllFileTabs,
      handleCloseFileCompare: source.handleCloseFileCompare,
      handleCloseFileHistory: source.handleCloseFileHistory,
      handleCloseFileTab: source.handleCloseFileTab,
      handleCloseOtherFileHistories: source.handleCloseOtherFileHistories,
      handleCloseOtherFileTabs: source.handleCloseOtherFileTabs,
      handleExitEditor: source.handleExitEditor,
      handleOpenDetachedFileExplorer: source.handleOpenDetachedFileExplorer,
      handleOpenFile: source.handleOpenFile,
      handleOpenFileHistory: source.handleOpenFileHistory,
      handleOpenScratchFileCompare: source.handleOpenScratchFileCompare,
      handleOpenWorkspaceFileCompare: source.handleOpenWorkspaceFileCompare,
      handleReorderFileTabs: source.handleReorderFileTabs,
      handleSelectDiff: source.handleSelectDiff,
      handleSelectOpenAppId: source.handleSelectOpenAppId,
      isEditorFileMaximized: source.isEditorFileMaximized,
      isFilesLoading: source.isFilesLoading,
      renameWorktreeUpstream: source.renameWorktreeUpstream,
      renameWorktreeUpstreamPrompt: source.renameWorktreeUpstreamPrompt,
      resetGitHubPanelState: source.resetGitHubPanelState,
      resetSoloSplitToHalf: source.resetSoloSplitToHalf,
      resetWorkspaceThreads: source.resetWorkspaceThreads,
      resolveCloneProjectContext: source.resolveCloneProjectContext,
      resolveCanonicalThreadId: source.resolveCanonicalThreadId,
      resolveComposerSelectionForThread: source.resolveComposerSelectionForThread,
      resolveOpenCodeAgentForThread: source.resolveOpenCodeAgentForThread,
      resolveOpenCodeVariantForThread: source.resolveOpenCodeVariantForThread,
      restartTerminalSession: source.restartTerminalSession,
      retryReleaseNotesLoad: source.retryReleaseNotesLoad,
      reviewPrompt: source.reviewPrompt,
      rightPanelCollapsed: source.rightPanelCollapsed,
      rightPanelWidth: source.rightPanelWidth,
      scaleShortcutText: source.scaleShortcutText,
      scaleShortcutTitle: source.scaleShortcutTitle,
      scanGitRoots: source.scanGitRoots,
      scopedKanbanTasks: source.scopedKanbanTasks,
      searchContentFilters: source.searchContentFilters,
      searchApiHydrationStatus: source.searchApiHydrationStatus,
      searchFileHydrationStatus: source.searchFileHydrationStatus,
      searchPaletteQuery: source.searchPaletteQuery,
      searchPaletteSelectedIndex: source.searchPaletteSelectedIndex,
      searchResults: source.searchResults,
      searchScope: source.searchScope,
      selectBranch: source.selectBranch,
      selectBranchAtIndex: source.selectBranchAtIndex,
      selectCommit: source.selectCommit,
      selectCommitAtIndex: source.selectCommitAtIndex,
      selectHome: source.selectHome,
      selectWorkspace: source.selectWorkspace,
      selectedAgent: source.selectedAgent,
      selectedCommitSha: source.selectedCommitSha,
      selectedDiffPath: source.selectedDiffPath,
      selectedAgentRef: source.selectedAgentRef,
      selectedKanbanTaskId: source.selectedKanbanTaskId,
      selectedOpenCodeAgent: source.selectedOpenCodeAgent,
      selectedOpenCodeVariant: source.selectedOpenCodeVariant,
      selectedPullRequest: source.selectedPullRequest,
    },
    settingsContext: {
      sendUserMessageToThread: source.sendUserMessageToThread,
      setAccessMode: source.setAccessMode,
      setActiveEditorLineRange: source.setActiveEditorLineRange,
      setActiveEngine: source.setActiveEngine,
      setActiveTab: source.setActiveTab,
      setActiveThreadId: source.setActiveThreadId,
      setActiveWorkspaceId: source.setActiveWorkspaceId,
      setAppMode: source.setAppMode,
      setAppSettings: source.setAppSettings,
      setCenterMode: source.setCenterMode,
      setDebugOpen: source.setDebugOpen,
      setDiffSource: source.setDiffSource,
      setEditorSplitCompanion: source.setEditorSplitCompanion,
      setEditorSplitLayout: source.setEditorSplitLayout,
      setEngineSelectedModelIdByType: source.setEngineSelectedModelIdByType,
      setFilePanelMode: source.setFilePanelMode,
      setFileReferenceMode: source.setFileReferenceMode,
      setGitDiffListView: source.setGitDiffListView,
      setGitDiffViewStyle: source.setGitDiffViewStyle,
      setGitHistoryPanelHeight: source.setGitHistoryPanelHeight,
      setGitPanelMode: source.setGitPanelMode,
      setGitRootScanDepth: source.setGitRootScanDepth,
      setGlobalSearchFilesByWorkspace: source.setGlobalSearchFilesByWorkspace,
      setHighlightedBranchIndex: source.setHighlightedBranchIndex,
      setHighlightedCommitIndex: source.setHighlightedCommitIndex,
      setHighlightedPresetIndex: source.setHighlightedPresetIndex,
      setIsEditorFileMaximized: source.setIsEditorFileMaximized,
      setIsPanelLocked: source.setIsPanelLocked,
      setIsPlanPanelDismissed: source.setIsPlanPanelDismissed,
      setIsSearchPaletteOpen: source.setIsSearchPaletteOpen,
      setKanbanViewState: source.setKanbanViewState,
      setLiveEditPreviewEnabled: source.setLiveEditPreviewEnabled,
      setReduceTransparency: source.setReduceTransparency,
      setWindowTransparencyEnabled: source.setWindowTransparencyEnabled,
      setWindowOpacity: source.setWindowOpacity,
      setRightPanelWidth: source.setRightPanelWidth,
      setSearchContentFilters: source.setSearchContentFilters,
      setSearchPaletteQuery: source.setSearchPaletteQuery,
      setSearchPaletteSelectedIndex: source.setSearchPaletteSelectedIndex,
      setSearchScope: source.setSearchScope,
      setSelectedCommitSha: source.setSelectedCommitSha,
      setSelectedDiffPath: source.setSelectedDiffPath,
      setSelectedKanbanTaskId: source.setSelectedKanbanTaskId,
      setSelectedPullRequest: source.setSelectedPullRequest,
      setHomeOpen: source.setHomeOpen,
      setWorkspaceHomeWorkspaceId: source.setWorkspaceHomeWorkspaceId,
      settingsHighlightTarget: source.settingsHighlightTarget,
      settingsOpen: source.settingsOpen,
      settingsSection: source.settingsSection,
      loadingProgressDialog: source.loadingProgressDialog,
      dismissLoadingProgressDialog: source.dismissLoadingProgressDialog,
      shouldLoadDiffs: source.shouldLoadDiffs,
      shouldLoadGitHubPanelData: source.shouldLoadGitHubPanelData,
      showLoadingProgressDialog: source.showLoadingProgressDialog,
      hideLoadingProgressDialog: source.hideLoadingProgressDialog,
      showDebugButton: source.showDebugButton,
      showGitHistory: source.showGitHistory,
      showExtensions: source.showExtensions,
      showHome: source.showHome,
      showKanban: source.showKanban,
      showNextReleaseNotes: source.showNextReleaseNotes,
      showPresetStep: source.showPresetStep,
      showPreviousReleaseNotes: source.showPreviousReleaseNotes,
      showWorkspaceHome: source.showWorkspaceHome,
      sidebarCollapsed: source.sidebarCollapsed,
      sidebarWidth: source.sidebarWidth,
      startCompact: source.startCompact,
      startThreadForWorkspace: source.startThreadForWorkspace,
      startSharedSessionForWorkspace: source.startSharedSessionForWorkspace,
      startUpdate: source.startUpdate,
      syncError: source.syncError,
      syncLoading: source.syncLoading,
      t: source.t,
      tabletTab: source.tabletTab,
      terminalOpen: source.terminalOpen,
      terminalPanelHeight: source.terminalPanelHeight,
      terminalState: source.terminalState,
      terminalTabs: source.terminalTabs,
      threadAccessMode: source.threadAccessMode,
      threadItemsByThread: source.threadItemsByThread,
      threadListLoadingByWorkspace: source.threadListLoadingByWorkspace,
      threadStatusById: source.threadStatusById,
      threadsByWorkspace: source.threadsByWorkspace,
      toggleCompletionEmailIntent: source.toggleCompletionEmailIntent,
      triggerAutoThreadTitle: source.triggerAutoThreadTitle,
      ungroupedLabel: source.ungroupedLabel,
      unpinThread: source.unpinThread,
      updateThreadParent: source.updateThreadParent,
      updateCloneCopyName: source.updateCloneCopyName,
      updateCustomInstructions: source.updateCustomInstructions,
      updatePrompt: source.updatePrompt,
      updateWorkspaceCodexBin: source.updateWorkspaceCodexBin,
      updateWorkspaceSettings: source.updateWorkspaceSettings,
      updateWorktreeBaseRef: source.updateWorktreeBaseRef,
      updateWorktreeBranch: source.updateWorktreeBranch,
      updateWorktreePublishToOrigin: source.updateWorktreePublishToOrigin,
      updateWorktreeSetupScript: source.updateWorktreeSetupScript,
      updaterState: source.updaterState,
      useSuggestedCloneCopiesFolder: source.useSuggestedCloneCopiesFolder,
      userInputRequests: source.userInputRequests,
      workspaceActivity: source.workspaceActivity,
      workspaceDropTargetRef: source.workspaceDropTargetRef,
      workspaceFilesPollingEnabled: source.workspaceFilesPollingEnabled,
      workspaceGroups: source.workspaceGroups,
      workspaceHomeWorkspaceId: source.workspaceHomeWorkspaceId,
      workspaceNameByPath: source.workspaceNameByPath,
      homeWorkspaceDefaultId: source.homeWorkspaceDefaultId,
      homeWorkspaceSelectedId: source.homeWorkspaceSelectedId,
      workspaceSearchSources: source.workspaceSearchSources,
      workspaces: source.workspaces,
      workspacesById: source.workspacesById,
      workspacesByPath: source.workspacesByPath,
      worktreeApplyError: source.worktreeApplyError,
      worktreeApplyLoading: source.worktreeApplyLoading,
      worktreeApplySuccess: source.worktreeApplySuccess,
      worktreeCreateResult: source.worktreeCreateResult,
      worktreeLabel: source.worktreeLabel,
      worktreePrompt: source.worktreePrompt,
      worktreeRename: source.worktreeRename,
      worktreeSetupScriptState: source.worktreeSetupScriptState,
      sessionRadarRunningSessions: source.sessionRadarRunningSessions,
      sessionRadarRecentCompletedSessions:
        source.sessionRadarRecentCompletedSessions,
      runningSessionCountByWorkspaceId:
        source.runningSessionCountByWorkspaceId,
      recentCompletedSessionCountByWorkspaceId:
        source.recentCompletedSessionCountByWorkspaceId,
    },
    runtimeContext: buildRuntimeDomainContextSlice({
      runtimeRunState: source.runtimeRunState,
    }),
    modelSelectionContext: buildModelSelectionDomainContextSlice({
      effectiveModels: source.effectiveModels,
      effectiveReasoningSupported: source.effectiveReasoningSupported,
      effectiveSelectedModel: source.effectiveSelectedModel,
      effectiveSelectedModelId: source.effectiveSelectedModelId,
      providerModelCatalogs: source.providerModelCatalogs,
      reasoningOptions: source.effectiveReasoningOptions,
      reasoningSupported: source.effectiveReasoningSupported,
      refreshEngineModels: source.refreshEngineModels,
      resolvedEffort: source.resolvedEffort,
      resolvedModel: source.resolvedModel,
      selectedEffort: source.effectiveSelectedEffort,
      selectedModelId: source.effectiveSelectedModelId,
      setSelectedEffort: source.handleSelectComposerEffort,
      setSelectedModelId: source.setSelectedModelId,
      // S4 PR-C：模型/engine 选择动作（从 composerContext 归位）
      availableEngines: source.availableEngines,
      handleOpenModelSettings: source.handleOpenModelSettings,
      handleRefreshModelConfig: source.handleRefreshModelConfig,
      handleSelectModel: source.handleSelectModel,
      handleSelectOpenCodeAgent: source.handleSelectOpenCodeAgent,
      handleSelectOpenCodeVariant: source.handleSelectOpenCodeVariant,
      isModelConfigRefreshing: source.isModelConfigRefreshing,
    }),
    collaborationModeContext: buildCollaborationModeDomainContextSlice({
      applySelectedCollaborationMode: source.applySelectedCollaborationMode,
      collaborationModePayload: source.collaborationModePayload,
      collaborationModes: source.collaborationModes,
      collaborationModesEnabled: source.collaborationModesEnabled,
      collaborationRuntimeModeByThread: source.collaborationRuntimeModeByThread,
      collaborationUiModeByThread: source.collaborationUiModeByThread,
      handleCollaborationModeResolved: source.handleCollaborationModeResolved,
      resolveCollaborationRuntimeMode: source.resolveCollaborationRuntimeMode,
      resolveCollaborationUiMode: source.resolveCollaborationUiMode,
      selectedCollaborationMode: source.selectedCollaborationMode,
      selectedCollaborationModeId: source.selectedCollaborationModeId,
      setCodexCollaborationMode: source.setCodexCollaborationMode,
      setCollaborationRuntimeModeByThread: source.setCollaborationRuntimeModeByThread,
      setCollaborationUiModeByThread: source.setCollaborationUiModeByThread,
      setSelectedCollaborationModeId: source.setSelectedCollaborationModeId,
    }),
  }
  );
}

export function useAppShellDomainAssembly(
  source: AppShellDomainAssemblySource,
): AppShellDomainContexts {
  const previousRef = useRef<AppShellDomainContexts | null>(null);
  const raw = assembleAppShellDomainContexts(source);
  const stable = reuseStableAppShellDomainContexts(previousRef.current, raw);
  useEffect(() => {
    previousRef.current = stable;
  }, [stable]);
  return stable;
}
