// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "Falha na conexão",
    "requestFailed": "Falha na solicitação",
    "unexpectedError": "Ocorreu um erro inesperado",
    "sessionExpired": "Sessão expirada",
    "rateLimited": "Limite de taxa atingido. Tente novamente mais tarde.",
    "networkError": "Erro de rede. Verifique sua conexão.",
    "failedToAddWorkspace": "Falha ao adicionar workspace.",
    "failedToOpenNewWindow": "Falha ao abrir uma nova janela.",
    "failedToCreateSession": "Falha ao criar sessão.",
    "failedToCreateSessionNoThreadId": "O runtime não retornou um novo id de sessão.",
    "failedToCreateSessionRuntimeRecovering": "O runtime estava reiniciando ao criar esta sessão. O app já tentou novamente uma vez. Reconecte o workspace e tente de novo.",
    "codexProviderWireApiUnsupported": "A versão atual do Codex CLI não oferece suporte a wire_api = \"chat\". Se este provedor oferecer suporte à Responses API, use wire_api = \"responses\". Se oferecer suporte apenas a Chat Completions, configure primeiro um serviço de conversão de protocolo ou router.",
    "codexProviderConfigInvalid": "A configuração deste provedor Codex não é um TOML válido. Verifique a sintaxe e use aspas retas inglesas (\") em vez de aspas tipográficas.",
    "reconnectAndRetryCreateSession": "Reconectar e tentar criar novamente",
    "reconnectingAndRetryingCreateSession": "Reconectando e tentando criar novamente...",
    "runtimeRecovered": "Runtime recuperado.",
    "retryingCreateSessionAfterRecovery": "Tentando criar sessão novamente...",
    "cliNotFound": "Nem o Claude Code CLI nem o Codex CLI foram encontrados. Instale um deles.",
    "cliNotFoundHint": "Instale o Claude Code: curl -fsSL https://claude.ai/install.sh | bash\nInstale o Codex: npm install -g @openai/codex",
    "codexCliNotFound": "Codex CLI não encontrado. Instale o Codex e certifique-se de que `codex` esteja no seu PATH.",
    "couldntOpenWorkspace": "Não foi possível abrir o workspace",
    "dismissError": "Dispensar erro",
    "applicationErrorTitle": "Application Error",
    "applicationErrorDescription": "An unexpected error stopped the UI. Copy the diagnostic report below, send it to the developers, then reload the app.",
    "applicationErrorReload": "Reload",
    "applicationErrorCopyReport": "Copy error report",
    "applicationErrorCopyDone": "Error report copied. Paste it into your feedback.",
    "applicationErrorCopyDownloaded": "Clipboard unavailable. A report file was downloaded instead — attach it when you report the issue.",
    "applicationErrorCopyFailed": "Could not copy or download the report. Select the text below and copy it manually.",
    "applicationErrorDetails": "Error details",
    "applicationErrorFeedbackTitle": "How to report this to developers",
    "applicationErrorFeedbackStep1": "Click “Copy error report”.",
    "applicationErrorFeedbackStep2": "Open the feedback page and create a new issue, then paste the report.",
    "applicationErrorFeedbackStep3": "Add what you were doing (cold start / streaming / switching workspace, etc.) and whether Reload recovers it.",
    "applicationErrorOpenFeedback": "Open feedback page",
    "applicationErrorMeta": "version: {{version}} · class: {{errorClass}} · platform: {{platform}}",
    "applicationErrorMessageLabel": "Error message",
    "applicationErrorDecodedLabel": "Decoded React #{{code}}",
    "applicationErrorComponentStackLabel": "Component stack",
    "applicationErrorStackLabel": "JavaScript stack"
  }
};

export default errors;
