import { useEffect } from "react";
import { useGitPanelController } from "../../features/app/hooks/useGitPanelController";
import { useGitRemote } from "../../features/git/hooks/useGitRemote";
import { useGitRepoScan } from "../../features/git/hooks/useGitRepoScan";
import { useAutoExitEmptyDiff } from "../../features/git/hooks/useAutoExitEmptyDiff";
import { useGitHubPanelController } from "../../features/app/hooks/useGitHubPanelController";
import { useSyncSelectedDiffPath } from "../../features/app/hooks/useSyncSelectedDiffPath";
import { useGitCommitController } from "../../features/app/hooks/useGitCommitController";
import { useMultiRepositoryGitStatus } from "../../features/git/hooks/useMultiRepositoryGitStatus";
import { resolveShouldLoadGitHubPanelData } from "../domains/gitHubPanelGating";
import { useGitSurfaceRepositoryActionsHost } from "../domains/useGitSurfaceRepositoryActionsHost";
import { useAppShellGitWorkspaceOpsSection } from "../sections/useAppShellGitWorkspaceOpsSection";
import { resolveAppShellFeatureActivation } from "./appShellFeatureActivation";
import { useHostFields, usePublishHostSlice } from "./appShellHostBus";

const SESSION_FIELDS = [
  "activeTab",
  "activeWorkspace",
  "activeWorkspaceId",
  "addDebugEntry",
  "appMode",
  "appSettings",
  "handleOpenGitHistoryFromFileHistory",
  "isCompact",
  "isTablet",
  "requestEditorOpenLayout",
  "rightPanelCollapsed",
  "setActiveEditorLineRange",
  "setActiveTab",
  "setIsEditorFileMaximized",
  "t",
  "tabletTab",
  "updateWorkspaceSettings",
] as const;

const RUNTIME_FIELDS = ["activeThreadId"] as const;

/** 刀 3 + 刀 2：git 表面 Host，非 git 表面跳过 remote / multi-repo IO。 */
export function useAppShellGitSurfaceHost() {
  const session = useHostFields("session", SESSION_FIELDS);
  const runtime = useHostFields("runtime", RUNTIME_FIELDS);
  const activeThreadId = (runtime.activeThreadId ?? null) as string | null;
  const activeTab = session.activeTab as any;
  const activeWorkspace = session.activeWorkspace as any;
  const activeWorkspaceId = session.activeWorkspaceId as any;
  const addDebugEntry = session.addDebugEntry as any;
  const appMode = session.appMode as any;
  const appSettings = session.appSettings as any;
  const handleOpenGitHistoryFromFileHistory = session.handleOpenGitHistoryFromFileHistory as any;
  const isCompact = session.isCompact as boolean;
  const isTablet = session.isTablet as boolean;
  const requestEditorOpenLayout = session.requestEditorOpenLayout as any;
  const rightPanelCollapsed = session.rightPanelCollapsed as boolean;
  const setActiveEditorLineRange = session.setActiveEditorLineRange as any;
  const setActiveTab = session.setActiveTab as any;
  const setIsEditorFileMaximized = session.setIsEditorFileMaximized as any;
  const t = session.t as any;
  const tabletTab = session.tabletTab as any;
  const updateWorkspaceSettings = session.updateWorkspaceSettings as any;
  const activation = resolveAppShellFeatureActivation({
    appMode,
    isSearchPaletteOpen: false,
  });

  const {
    gitIssues,
    gitIssuesTotal,
    gitIssuesLoading,
    gitIssuesError,
    gitPullRequests,
    gitPullRequestsTotal,
    gitPullRequestsLoading,
    gitPullRequestsError,
    gitPullRequestDiffs,
    gitPullRequestDiffsLoading,
    gitPullRequestDiffsError,
    gitPullRequestComments,
    gitPullRequestCommentsLoading,
    gitPullRequestCommentsError,
    handleGitIssuesChange,
    handleGitPullRequestsChange,
    handleGitPullRequestDiffsChange,
    handleGitPullRequestCommentsChange,
    resetGitHubPanelState,
  } = useGitHubPanelController();

  const {
    centerMode,
    setCenterMode,
    selectedDiffPath,
    setSelectedDiffPath,
    diffScrollRequestId,
    gitPanelMode,
    setGitPanelMode,
    gitDiffViewStyle,
    setGitDiffViewStyle,
    gitDiffListView,
    setGitDiffListView,
    filePanelMode,
    setFilePanelMode,
    selectedPullRequest,
    setSelectedPullRequest,
    selectedCommitSha,
    setSelectedCommitSha,
    diffSource,
    setDiffSource,
    gitStatus,
    refreshGitStatus,
    queueGitStatusRefresh,
    refreshGitDiffs,
    gitLogEntries,
    gitLogTotal,
    gitLogAhead,
    gitLogBehind,
    gitLogAheadEntries,
    gitLogBehindEntries,
    gitLogUpstream,
    gitLogLoading,
    gitLogError,
    refreshGitLog,
    gitCommitDiffs,
    shouldLoadDiffs,
    activeDiffs,
    activeDiffLoading,
    activeDiffError,
    handleSelectDiff,
    handleSelectCommit,
    handleActiveDiffPath,
    handleGitPanelModeChange,
    activeEditorFilePath,
    editorSplitCompanion,
    setEditorSplitCompanion,
    editorNavigationTarget,
    editorHighlightTarget,
    fileCompareSession,
    fileHistoryTabs,
    activeGitHistoryTabId,
    openFileTabs,
    handleOpenFile,
    handleOpenWorkspaceFileCompare,
    handleOpenScratchFileCompare,
    handleCloseFileCompare,
    handleOpenFileHistory,
    handleActivateGitHistoryTab,
    handleCloseFileHistory,
    handleCloseOtherFileHistories,
    handleCloseAllFileHistories,
    handleActivateFileTab,
    handleCloseFileTab,
    handleCloseOtherFileTabs,
    handleCloseAllFileTabs,
    handleReorderFileTabs,
    handleExitEditor,
    activeWorkspaceIdRef,
    activeWorkspaceRef,
  } = useGitPanelController({
    activeWorkspace,
    gitDiffPreloadEnabled: appSettings.preloadGitDiffs,
    isCompact,
    isTablet,
    rightPanelCollapsed,
    activeTab,
    tabletTab,
    setActiveTab,
    prDiffs: gitPullRequestDiffs,
    prDiffsLoading: gitPullRequestDiffsLoading,
    prDiffsError: gitPullRequestDiffsError,
    onOpenEditorLayoutRequest: requestEditorOpenLayout,
    onOpenGitHistoryRequest: handleOpenGitHistoryFromFileHistory,
    appMode,
  });

  useEffect(() => {
    if (!activeEditorFilePath) {
      setActiveEditorLineRange(null);
      setIsEditorFileMaximized(false);
    }
  }, [
    activeEditorFilePath,
    setActiveEditorLineRange,
    setIsEditorFileMaximized,
  ]);

  const shouldLoadGitHubPanelData = resolveShouldLoadGitHubPanelData({
    gitPanelMode,
    shouldLoadDiffs,
    diffSource,
  });

  useEffect(() => {
    resetGitHubPanelState();
  }, [activeWorkspaceId, resetGitHubPanelState]);
  const { remote: gitRemoteUrl } = useGitRemote(activeWorkspace, {
    enabled: activation.isGitRemoteEnabled,
  });
  const {
    repos: gitRootCandidates,
    isLoading: gitRootScanLoading,
    error: gitRootScanError,
    depth: gitRootScanDepth,
    hasScanned: gitRootScanHasScanned,
    scan: scanGitRoots,
    setDepth: setGitRootScanDepth,
    clear: clearGitRootCandidates,
  } = useGitRepoScan(activeWorkspace);

  const {
    activeGitRoot,
    alertError,
    branches,
    branchError,
    currentBranch,
    localBranches,
    remoteBranches,
    repositories,
    repositoriesLoading,
    repositoryError,
    refreshRepositories,
    selectedRepositoryRoot,
    selectRepository,
    fileStatus,
    handleApplyWorktreeChanges,
    handleCheckoutBranch,
    handleCreateBranch,
    handleUpdateBranch,
    handleUpdateAllRepositories,
    handleCheckoutAllRepositories,
    handleLoadCommonRepositoryBranches,
    handleOpenDetachedFileExplorer,
    handlePickGitRoot,
    handleRevertAllGitChanges,
    handleRevertGitFile,
    handleRevertGitPaths,
    handleSetGitRoot,
    handleStageGitAll,
    handleStageGitFile,
    handleUnstageGitAll,
    handleUnstageGitFile,
    handleUnstageGitPaths,
    worktreeApplyError,
    worktreeApplyLoading,
    worktreeApplySuccess,
  } = useAppShellGitWorkspaceOpsSection({
    activeWorkspace,
    addDebugEntry,
    clearGitRootCandidates,
    gitStatus,
    refreshGitDiffs,
    refreshGitStatus,
    t,
    updateWorkspaceSettings,
  });

  useSyncSelectedDiffPath({
    diffSource,
    centerMode,
    gitPullRequestDiffs,
    gitCommitDiffs,
    selectedDiffPath,
    setSelectedDiffPath,
  });

  useAutoExitEmptyDiff({
    centerMode,
    autoExitEnabled: diffSource === "local",
    activeDiffCount: activeDiffs.length,
    activeDiffLoading,
    activeDiffError,
    activeThreadId,
    isCompact,
    setCenterMode,
    setSelectedDiffPath,
    setActiveTab,
  });

  const {
    statuses: repositoryStatuses,
    isLoading: repositoryStatusesLoading,
    isMultiRepository,
    refresh: refreshRepositoryStatuses,
  } = useMultiRepositoryGitStatus(activeWorkspace, repositories, {
    enabled: activation.isMultiRepositoryStatusEnabled,
  });
  const {
    handleStageRepositoryFile,
    handleUnstageRepositoryFile,
    handleUnstageRepositoryAll,
    handleUnstageRepositoryFiles,
    handleRevertRepositoryFile,
    handleRevertRepositoryFiles,
    handleStageRepositoryAll,
  } = useGitSurfaceRepositoryActionsHost({ activeWorkspace });

  const {
    commitMessage,
    commitMessageLoading,
    commitMessageError,
    commitLoading,
    pushLoading,
    syncLoading,
    commitError,
    pushError,
    syncError,
    repositoryCommitSummary,
    onCommitMessageChange: handleCommitMessageChange,
    onGenerateCommitMessage: handleGenerateCommitMessage,
    onCommit: handleCommit,
    onCommitAndPush: handleCommitAndPush,
    onCommitAndSync: handleCommitAndSync,
    onPush: handlePush,
    onSync: handleSync,
    onCommitRepositories: handleCommitRepositories,
    clearOperationErrors: clearGitOperationErrors,
  } = useGitCommitController({
    activeWorkspace,
    activeWorkspaceId,
    activeWorkspaceIdRef,
    gitStatus,
    refreshGitStatus,
    refreshGitLog,
    onMutationComplete: refreshRepositories,
    repositoryStatuses,
    refreshRepositoryStatuses,
  });

  const git = {
    gitIssues,
    gitIssuesTotal,
    gitIssuesLoading,
    gitIssuesError,
    gitPullRequests,
    gitPullRequestsTotal,
    gitPullRequestsLoading,
    gitPullRequestsError,
    gitPullRequestDiffs,
    gitPullRequestDiffsLoading,
    gitPullRequestDiffsError,
    gitPullRequestComments,
    gitPullRequestCommentsLoading,
    gitPullRequestCommentsError,
    handleGitIssuesChange,
    handleGitPullRequestsChange,
    handleGitPullRequestDiffsChange,
    handleGitPullRequestCommentsChange,
    resetGitHubPanelState,
    centerMode,
    setCenterMode,
    selectedDiffPath,
    setSelectedDiffPath,
    diffScrollRequestId,
    gitPanelMode,
    setGitPanelMode,
    gitDiffViewStyle,
    setGitDiffViewStyle,
    gitDiffListView,
    setGitDiffListView,
    filePanelMode,
    setFilePanelMode,
    selectedPullRequest,
    setSelectedPullRequest,
    selectedCommitSha,
    setSelectedCommitSha,
    diffSource,
    setDiffSource,
    gitStatus,
    refreshGitStatus,
    queueGitStatusRefresh,
    refreshGitDiffs,
    gitLogEntries,
    gitLogTotal,
    gitLogAhead,
    gitLogBehind,
    gitLogAheadEntries,
    gitLogBehindEntries,
    gitLogUpstream,
    gitLogLoading,
    gitLogError,
    refreshGitLog,
    gitCommitDiffs,
    shouldLoadDiffs,
    activeDiffs,
    activeDiffLoading,
    activeDiffError,
    handleSelectDiff,
    handleSelectCommit,
    handleActiveDiffPath,
    handleGitPanelModeChange,
    activeEditorFilePath,
    editorSplitCompanion,
    setEditorSplitCompanion,
    editorNavigationTarget,
    editorHighlightTarget,
    fileCompareSession,
    fileHistoryTabs,
    activeGitHistoryTabId,
    openFileTabs,
    handleOpenFile,
    handleOpenWorkspaceFileCompare,
    handleOpenScratchFileCompare,
    handleCloseFileCompare,
    handleOpenFileHistory,
    handleActivateGitHistoryTab,
    handleCloseFileHistory,
    handleCloseOtherFileHistories,
    handleCloseAllFileHistories,
    handleActivateFileTab,
    handleCloseFileTab,
    handleCloseOtherFileTabs,
    handleCloseAllFileTabs,
    handleReorderFileTabs,
    handleExitEditor,
    activeWorkspaceIdRef,
    activeWorkspaceRef,
    shouldLoadGitHubPanelData,
    gitRemoteUrl,
    gitRootCandidates,
    gitRootScanLoading,
    gitRootScanError,
    gitRootScanDepth,
    gitRootScanHasScanned,
    scanGitRoots,
    setGitRootScanDepth,
    clearGitRootCandidates,
    activeGitRoot,
    alertError,
    branches,
    branchError,
    currentBranch,
    localBranches,
    remoteBranches,
    repositories,
    repositoriesLoading,
    repositoryError,
    refreshRepositories,
    selectedRepositoryRoot,
    selectRepository,
    fileStatus,
    handleApplyWorktreeChanges,
    handleCheckoutBranch,
    handleCreateBranch,
    handleUpdateBranch,
    handleUpdateAllRepositories,
    handleCheckoutAllRepositories,
    handleLoadCommonRepositoryBranches,
    handleOpenDetachedFileExplorer,
    handlePickGitRoot,
    handleRevertAllGitChanges,
    handleRevertGitFile,
    handleRevertGitPaths,
    handleSetGitRoot,
    handleStageGitAll,
    handleStageGitFile,
    handleUnstageGitAll,
    handleUnstageGitFile,
    handleUnstageGitPaths,
    worktreeApplyError,
    worktreeApplyLoading,
    worktreeApplySuccess,
    repositoryStatuses,
    repositoryStatusesLoading,
    isMultiRepository,
    refreshRepositoryStatuses,
    handleStageRepositoryFile,
    handleUnstageRepositoryFile,
    handleUnstageRepositoryAll,
    handleUnstageRepositoryFiles,
    handleRevertRepositoryFile,
    handleRevertRepositoryFiles,
    handleStageRepositoryAll,
    commitMessage,
    commitMessageLoading,
    commitMessageError,
    commitLoading,
    pushLoading,
    syncLoading,
    commitError,
    pushError,
    syncError,
    repositoryCommitSummary,
    handleCommitMessageChange,
    handleGenerateCommitMessage,
    handleCommit,
    handleCommitAndPush,
    handleCommitAndSync,
    handlePush,
    handleSync,
    handleCommitRepositories,
    clearGitOperationErrors,
  };
  usePublishHostSlice("git", git);
  return git;
}
