// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "接続に失敗しました",
    "requestFailed": "リクエストに失敗しました",
    "unexpectedError": "予期しないエラーが発生しました",
    "sessionExpired": "セッションの有効期限が切れました",
    "rateLimited": "レート制限に達しました。後でもう一度お試しください。",
    "networkError": "ネットワークエラーです。接続を確認してください。",
    "failedToAddWorkspace": "ワークスペースの追加に失敗しました。",
    "failedToOpenNewWindow": "新しいウィンドウを開けませんでした。",
    "failedToCreateSession": "セッションの作成に失敗しました。",
    "failedToCreateSessionNoThreadId": "ランタイムが新しいセッション ID を返しませんでした。",
    "failedToCreateSessionRuntimeRecovering": "このセッションの作成中にランタイムが再起動していました。アプリはすでに一度再試行しました。ワークスペースを再接続して、もう一度お試しください。",
    "codexProviderWireApiUnsupported": "現在の Codex CLI は wire_api = \"chat\" をサポートしていません。このプロバイダーが Responses API をサポートする場合は wire_api = \"responses\" を使用してください。Chat Completions のみをサポートする場合は、先にプロトコル変換サービスまたは router を設定してください。",
    "codexProviderConfigInvalid": "この Codex プロバイダー設定は有効な TOML ではありません。構文を確認し、スマートクォートではなく半角の英語直線引用符 (\") を使用してください。",
    "reconnectAndRetryCreateSession": "再接続して作成を再試行",
    "reconnectingAndRetryingCreateSession": "再接続して作成を再試行中...",
    "runtimeRecovered": "ランタイムが復旧しました。",
    "retryingCreateSessionAfterRecovery": "セッションの作成を再試行中...",
    "cliNotFound": "Claude Code CLI と Codex CLI のどちらも見つかりませんでした。いずれかをインストールしてください。",
    "cliNotFoundHint": "Claude Code をインストール：curl -fsSL https://claude.ai/install.sh | bash\nCodex をインストール：npm install -g @openai/codex",
    "codexCliNotFound": "Codex CLI が見つかりません。Codex をインストールし、`codex` が PATH に含まれていることを確認してください。",
    "couldntOpenWorkspace": "ワークスペースを開けませんでした",
    "dismissError": "エラーを閉じる",
    "applicationErrorTitle": "Application Error",
    "applicationErrorDescription": "An unexpected error stopped the UI. Copy the diagnostic report below, send it to the developers, then reload the app.",
    "applicationErrorReload": "Reload",
    "applicationErrorCopyReport": "Copy error report",
    "applicationErrorCopyDone": "Error report copied. Paste it into your feedback.",
    "applicationErrorCopyDownloaded": "Clipboard unavailable. A report file was downloaded instead — attach it when you report the issue.",
    "applicationErrorCopyFailed": "Could not copy or download the report. Select the text below and copy it manually.",
    "applicationErrorDetails": "Error details",
    "applicationErrorFeedbackTitle": "How to report this to developers",
    "applicationErrorFeedbackStep1": "Click “Copy error report”.",
    "applicationErrorFeedbackStep2": "Open the feedback page and create a new issue, then paste the report.",
    "applicationErrorFeedbackStep3": "Add what you were doing (cold start / streaming / switching workspace, etc.) and whether Reload recovers it.",
    "applicationErrorOpenFeedback": "Open feedback page",
    "applicationErrorMeta": "version: {{version}} · class: {{errorClass}} · platform: {{platform}}",
    "applicationErrorMessageLabel": "Error message",
    "applicationErrorDecodedLabel": "Decoded React #{{code}}",
    "applicationErrorComponentStackLabel": "Component stack",
    "applicationErrorStackLabel": "JavaScript stack"
  }
};

export default errors;
