// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "Fallo de conexión",
    "requestFailed": "La solicitud falló",
    "unexpectedError": "Ocurrió un error inesperado",
    "sessionExpired": "La sesión expiró",
    "rateLimited": "Límite de solicitudes alcanzado. Inténtalo de nuevo más tarde.",
    "networkError": "Error de red. Comprueba tu conexión.",
    "failedToAddWorkspace": "No se pudo añadir el espacio de trabajo.",
    "failedToOpenNewWindow": "No se pudo abrir una nueva ventana.",
    "failedToCreateSession": "No se pudo crear la sesión.",
    "failedToCreateSessionNoThreadId": "El runtime no devolvió un nuevo id de sesión.",
    "failedToCreateSessionRuntimeRecovering": "El runtime se estaba reiniciando al crear esta sesión. La app ya reintentó una vez. Reconecta el espacio de trabajo e inténtalo de nuevo.",
    "codexProviderWireApiUnsupported": "La versión actual de Codex CLI no admite wire_api = \"chat\". Si este proveedor admite Responses API, usa wire_api = \"responses\". Si solo admite Chat Completions, configura primero un servicio de conversión de protocolo o router.",
    "codexProviderConfigInvalid": "La configuración de este proveedor de Codex no es TOML válido. Comprueba la sintaxis y usa comillas rectas inglesas (\") en lugar de comillas tipográficas.",
    "reconnectAndRetryCreateSession": "Reconectar y reintentar la creación",
    "reconnectingAndRetryingCreateSession": "Reconectando y reintentando la creación...",
    "runtimeRecovered": "Runtime recuperado.",
    "retryingCreateSessionAfterRecovery": "Reintentando la creación de la sesión...",
    "cliNotFound": "No se encontró ni la CLI de Claude Code ni la CLI de Codex. Instala una de ellas.",
    "cliNotFoundHint": "Instalar Claude Code: curl -fsSL https://claude.ai/install.sh | bash\nInstalar Codex: npm install -g @openai/codex",
    "codexCliNotFound": "No se encontró la CLI de Codex. Instala Codex y asegúrate de que `codex` esté en tu PATH.",
    "couldntOpenWorkspace": "No se pudo abrir el espacio de trabajo",
    "dismissError": "Descartar error",
    "applicationErrorTitle": "Application Error",
    "applicationErrorDescription": "An unexpected error stopped the UI. Copy the diagnostic report below, send it to the developers, then reload the app.",
    "applicationErrorReload": "Reload",
    "applicationErrorCopyReport": "Copy error report",
    "applicationErrorCopyDone": "Error report copied. Paste it into your feedback.",
    "applicationErrorCopyDownloaded": "Clipboard unavailable. A report file was downloaded instead — attach it when you report the issue.",
    "applicationErrorCopyFailed": "Could not copy or download the report. Select the text below and copy it manually.",
    "applicationErrorDetails": "Error details",
    "applicationErrorFeedbackTitle": "How to report this to developers",
    "applicationErrorFeedbackStep1": "Click “Copy error report”.",
    "applicationErrorFeedbackStep2": "Open the feedback page and create a new issue, then paste the report.",
    "applicationErrorFeedbackStep3": "Add what you were doing (cold start / streaming / switching workspace, etc.) and whether Reload recovers it.",
    "applicationErrorOpenFeedback": "Open feedback page",
    "applicationErrorMeta": "version: {{version}} · class: {{errorClass}} · platform: {{platform}}",
    "applicationErrorMessageLabel": "Error message",
    "applicationErrorDecodedLabel": "Decoded React #{{code}}",
    "applicationErrorComponentStackLabel": "Component stack",
    "applicationErrorStackLabel": "JavaScript stack"
  }
};

export default errors;
