import { useCallback, useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { useThreads } from "../../features/threads/hooks/useThreads";
import { resolveIsSharedSession } from "../../features/shared-session/utils/sharedSessionIdentity";
import { useGitPanelController } from "../../features/app/hooks/useGitPanelController";
import { useGitRemote } from "../../features/git/hooks/useGitRemote";
import { useGitRepoScan } from "../../features/git/hooks/useGitRepoScan";
import { useAutoExitEmptyDiff } from "../../features/git/hooks/useAutoExitEmptyDiff";
import { useModels } from "../../features/models/hooks/useModels";
import { useCollaborationModes } from "../../features/collaboration/hooks/useCollaborationModes";
import { useSkills } from "../../features/skills/hooks/useSkills";
import { useCustomCommands } from "../../features/commands/hooks/useCustomCommands";
import { useCustomPrompts } from "../../features/prompts/hooks/useCustomPrompts";
import { useWorkspaceFiles } from "../../features/workspaces/hooks/useWorkspaceFiles";
import { useDebugLog } from "../../features/debug/hooks/useDebugLog";
import { useWorkspaceRefreshOnFocus } from "../../features/workspaces/hooks/useWorkspaceRefreshOnFocus";
import { useWorkspaceRestore } from "../../features/workspaces/hooks/useWorkspaceRestore";
import { useLayoutController } from "../../features/app/hooks/useLayoutController";
import { useAppSettingsController } from "../../features/app/hooks/useAppSettingsController";
import { useUpdaterController } from "../../features/app/hooks/useUpdaterController";
import { useReleaseNotes } from "../../features/update/hooks/useReleaseNotes";
import { useErrorToasts } from "../../features/notifications/hooks/useErrorToasts";
import { useComposerEditorState } from "../../features/composer/hooks/useComposerEditorState";
import { useDictationController } from "../../features/app/hooks/useDictationController";
import { useComposerController } from "../../features/app/hooks/useComposerController";
import { useEngineController } from "../../features/engine/hooks/useEngineController";
import { useWorktreePrompt } from "../../features/workspaces/hooks/useWorktreePrompt";
import { useWorkspaceSelection } from "../../features/workspaces/hooks/useWorkspaceSelection";
import { useGitHubPanelController } from "../../features/app/hooks/useGitHubPanelController";
import { useSettingsModalState } from "../../features/app/hooks/useSettingsModalState";
import { useLoadingProgressDialogState } from "../../features/app/hooks/useLoadingProgressDialogState";
import { useSyncSelectedDiffPath } from "../../features/app/hooks/useSyncSelectedDiffPath";
import { useWorkspaceActions } from "../../features/app/hooks/useWorkspaceActions";
import { useLiquidGlassEffect } from "../../features/app/hooks/useLiquidGlassEffect";
import { useGitCommitController } from "../../features/app/hooks/useGitCommitController";
import { useMultiRepositoryGitStatus } from "../../features/git/hooks/useMultiRepositoryGitStatus";
import { normalizeFsPath } from "../../utils/workspacePaths";
import type { AppMode } from "../../types";
import { useCodeCssVars } from "../../features/app/hooks/useCodeCssVars";
import { useAccountSwitching } from "../../features/app/hooks/useAccountSwitching";
import { useRuntimeThreadDomainHost } from "../domains/useRuntimeThreadDomainHost";
import { useComposerEditorSettings } from "../domains/composerEditorSettings";
import { useComposerSelectionResolver } from "../domains/composerSelectionResolver";
import { resolveShouldLoadGitHubPanelData } from "../domains/gitHubPanelGating";
import { useGitSurfaceRepositoryActionsHost } from "../domains/useGitSurfaceRepositoryActionsHost";
import { resolveWorkspaceFilesLoadFlags } from "../domains/workspaceFilesGating";
import { useWorkspaceSessionHost } from "../domains/useWorkspaceSessionHost";
import { useComposerDomainHost } from "../domains/useComposerDomainHost";
import { useConversationDomainHost } from "../domains/useConversationDomainHost";
import { useKanbanDomainHost } from "../domains/useModeDomainHosts";
import { useAppShellPromptActionsSection } from "../sections/useAppShellPromptActionsSection";
import { useAppShellSearchRadarSection } from "../sections/useAppShellSearchRadarSection";
import { useGitStatusRefreshOnTurnSettle } from "../sections/useGitStatusRefreshOnTurnSettle";
import { useAppShellGitWorkspaceOpsSection } from "../sections/useAppShellGitWorkspaceOpsSection";
import { usePanelLockState } from "../sections/usePanelLockState";
import { useThreadScopedCollaborationMode } from "../domains/useThreadScopedCollaborationMode";
import { GitHubPanelData, SettingsView } from "../render/lazyViews";
import { useCreateSessionLoading } from "../sections/useCreateSessionLoading";
import type { AgentTaskScrollRequest } from "../../features/messages";
import { useAppShellWorkspaceFlowsSection } from "../sections/useAppShellWorkspaceFlowsSection";
import { useWorkspacePathsIntake } from "../sections/useWorkspacePathsIntake";
import { useAppShellWorktreeChromeSection } from "../sections/useAppShellWorktreeChromeSection";
import { useCollaborationModeThreadSync } from "../domains/useCollaborationModeThreadSync";
import { useAppShellViewStateSection } from "../sections/useAppShellViewStateSection";
import { defineAppShellRuntimeActions } from "../domains/appShellActionBoundaries";
import { useAppShellDomainAssembly } from "../domains/useAppShellDomainAssembly";
import { useAppShellComposerPrefsPersistence } from "../domains/useAppShellComposerPrefsPersistence";
import { useAppShellAccessModeSection } from "../sections/useAppShellAccessModeSection";
import { useAppShellDesktopChrome } from "../sections/useAppShellDesktopChrome";
import { useAppShellModelSettingsAction } from "../sections/useAppShellModelSettingsAction";
import { useAppShellEditorLayoutSection } from "../sections/useAppShellEditorLayoutSection";
import { useAppShellSearchPaletteSection } from "../sections/useAppShellSearchPaletteSection";
import { useAppShellQuickSwitcherSection } from "../sections/useAppShellQuickSwitcherSection";
import { useAppShellClaudeThinkingSection } from "../sections/useAppShellClaudeThinkingSection";
import { useMemoizedRuntimeThreadProviderValue } from "../domains/runtimeThreadProvider";
import { useMemoizedComposerProviderValue } from "../domains/composerProvider";
import { useMemoizedLayoutChromeProviderValue } from "../domains/layoutChromeProvider";


const RETIRED_OPENCODE_AGENTS = Object.freeze([]);
const resolveRetiredOpenCodeSelection = () => null;
const ignoreRetiredOpenCodeSelection = () => {};

/**
 * T2.6：AppShell 根 composition host。
 * 将原先 AppShell 函数体内的业务 hooks 下沉到此，使 `app-shell.tsx` 仅保留
 * composition + zone providers + view（根 hook 种类 ≤ 20）。
 */
export function useAppShellRootComposition() {
  const { t } = useTranslation();
  const handleOpenGitHistoryFromFileHistory = useCallback(() => {
    setAppMode("gitHistory");
  }, []);

  const {
    claudeThinkingVisible,
    handleResolvedClaudeThinkingVisibleChange,
  } = useAppShellClaudeThinkingSection();

  const {
    appSettings,
    setAppSettings,
    doctor,
    claudeDoctor,
    kimiDoctor,
    grokDoctor,
    opencodeDoctor,
    appSettingsLoading,
    reduceTransparency,
    setReduceTransparency,
    windowTransparencyEnabled,
    setWindowTransparencyEnabled,
    windowOpacity,
    setWindowOpacity,
    scaleShortcutTitle,
    scaleShortcutText,
    queueSaveSettings,
    increaseUiScale,
    decreaseUiScale,
    resetUiScale,
  } = useAppSettingsController();
  useCodeCssVars(appSettings);
  const {
    activeEngineRef,
    persistClaudeCollaborationMode,
    persistComposerEnginePref,
  } = useAppShellComposerPrefsPersistence({
    appSettings,
    appSettingsLoading,
  });
  const {
    dictationModel,
    dictationState,
    dictationLevel,
    dictationTranscript,
    dictationError,
    dictationHint,
    dictationReady,
    handleToggleDictation,
    clearDictationTranscript,
    clearDictationError,
    clearDictationHint,
  } = useDictationController(appSettings);
  const {
    debugOpen,
    setDebugOpen,
    debugEntries,
    showDebugButton,
    addDebugEntry,
    handleCopyDebug,
    clearDebugEntries,
  } = useDebugLog();
  useLiquidGlassEffect({
    reduceTransparency,
    onDebug: addDebugEntry,
  });
  const [activeTab, setActiveTab] = useState<
    "projects" | "codex" | "spec" | "git" | "log"
  >("codex");
  const tabletTab = activeTab === "projects" ? "codex" : activeTab;
  const {
    workspaces,
    workspaceGroups,
    groupedWorkspaces,
    getWorkspaceGroupName,
    ungroupedLabel,
    activeWorkspace,
    activeWorkspaceId,
    setActiveWorkspaceId,
    addWorkspace,
    addWorkspaceFromPath,
    addCloneAgent,
    addWorktreeAgent,
    connectWorkspace,
    markWorkspaceConnected,
    updateWorkspaceSettings,
    updateWorkspaceCodexBin,
    createWorkspaceGroup,
    renameWorkspaceGroup,
    moveWorkspaceGroup,
    deleteWorkspaceGroup,
    assignWorkspaceGroup,
    removeWorkspace,
    removeWorktree,
    renameWorktree,
    renameWorktreeUpstream,
    deletingWorktreeIds,
    hasLoaded,
    refreshWorkspaces,
    homeOpen,
    homeWorkspaceDefaultId,
    homeWorkspaceSelectedId,
    setHomeOpen,
    workspacesById,
    workspacesByPath,
  } = useWorkspaceSessionHost({
    appSettings,
    appSettingsLoading,
    addDebugEntry,
    queueSaveSettings,
  });
  const {
    sidebarWidth,
    rightPanelWidth,
    setRightPanelWidth,
    onSidebarResizeStart,
    onRightPanelResizeStart,
    planPanelHeight,
    onPlanPanelResizeStart,
    terminalPanelHeight,
    onTerminalPanelResizeStart,
    debugPanelHeight,
    onDebugPanelResizeStart,
    kanbanConversationWidth,
    onKanbanConversationResizeStart,
    isCompact,
    isTablet,
    isPhone,
    sidebarCollapsed,
    rightPanelCollapsed,
    collapseSidebar,
    expandSidebar,
    collapseRightPanel,
    expandRightPanel,
    terminalOpen,
    handleDebugClick,
    handleToggleTerminal,
    openTerminal,
    closeTerminal: closeTerminalPanel,
  } = useLayoutController({
    activeWorkspaceId,
    setActiveTab,
    setDebugOpen,
    toggleDebugPanelShortcut: appSettings.toggleDebugPanelShortcut,
    toggleTerminalShortcut: appSettings.toggleTerminalShortcut,
  });
  const [appMode, setAppMode] = useState<AppMode>("chat");
  const [agentTaskScrollRequest, setAgentTaskScrollRequest] =
    useState<AgentTaskScrollRequest | null>(null);
  const {
    activeEditorLineRange,
    appRootRef,
    editorSplitLayout,
    fileReferenceMode,
    gitHistoryPanelHeight,
    isEditorFileMaximized,
    liveEditPreviewEnabled,
    onGitHistoryPanelResizeStart,
    requestEditorOpenLayout,
    resetSoloSplitToHalf,
    setActiveEditorLineRange,
    setEditorSplitLayout,
    setFileReferenceMode,
    setIsEditorFileMaximized,
    setLiveEditPreviewEnabled,
  } = useAppShellEditorLayoutSection({
    collapseSidebar,
    setAppMode,
    setRightPanelWidth,
  });

  const {
    settingsOpen,
    settingsSection,
    settingsHighlightTarget,
    openSettings,
    closeSettings,
  } = useSettingsModalState();
  const {
    loadingProgressDialog,
    showLoadingProgressDialog,
    hideLoadingProgressDialog,
    dismissLoadingProgressDialog,
  } = useLoadingProgressDialogState();

  const runWithCreateSessionLoading = useCreateSessionLoading({
    hideLoadingProgressDialog,
    showLoadingProgressDialog,
    t,
  });

  const handleOpenModelSettings = useAppShellModelSettingsAction();

  const {
    globalSearchFilesByWorkspace, isSearchPaletteOpen, searchContentFilters,
    searchPaletteQuery, searchPaletteSelectedIndex, searchScope,
    setGlobalSearchFilesByWorkspace, setIsSearchPaletteOpen,
    setSearchContentFilters, setSearchPaletteQuery, setSearchPaletteSelectedIndex,
    setSearchScope,
  } = useAppShellSearchPaletteSection();
  const {
    isPanelLocked,
    handleLockPanel,
    handleUnlockPanel,
  } = usePanelLockState();
  const completionTrackerReadyRef = useRef(false);
  const completionTrackerBySessionRef = useRef<Record<string, any>>({});
  const composerInputRef = useRef<HTMLTextAreaElement | null>(null);

  const {
    updaterState,
    startUpdate,
    checkForUpdates,
    dismissUpdate,
    handleTestNotificationSound,
  } = useUpdaterController({
    notificationSoundsEnabled: appSettings.notificationSoundsEnabled,
    notificationSoundId: appSettings.notificationSoundId,
    notificationSoundCustomPath: appSettings.notificationSoundCustomPath,
    onDebug: addDebugEntry,
  });
  const {
    isOpen: releaseNotesOpen,
    entries: releaseNotesEntries,
    activeIndex: releaseNotesActiveIndex,
    loading: releaseNotesLoading,
    error: releaseNotesError,
    openReleaseNotes,
    closeReleaseNotes,
    goToPrevious: showPreviousReleaseNotes,
    goToNext: showNextReleaseNotes,
    retryLoad: retryReleaseNotesLoad,
  } = useReleaseNotes({
    onDebug: addDebugEntry,
  });

  const { errorToasts, dismissErrorToast } = useErrorToasts();
  const normalizePath = useCallback(
    (path: string) => normalizeFsPath(path).trim(),
    [],
  );

  const {
    gitIssues,
    gitIssuesTotal,
    gitIssuesLoading,
    gitIssuesError,
    gitPullRequests,
    gitPullRequestsTotal,
    gitPullRequestsLoading,
    gitPullRequestsError,
    gitPullRequestDiffs,
    gitPullRequestDiffsLoading,
    gitPullRequestDiffsError,
    gitPullRequestComments,
    gitPullRequestCommentsLoading,
    gitPullRequestCommentsError,
    handleGitIssuesChange,
    handleGitPullRequestsChange,
    handleGitPullRequestDiffsChange,
    handleGitPullRequestCommentsChange,
    resetGitHubPanelState,
  } = useGitHubPanelController();

  const {
    centerMode,
    setCenterMode,
    selectedDiffPath,
    setSelectedDiffPath,
    diffScrollRequestId,
    gitPanelMode,
    setGitPanelMode,
    gitDiffViewStyle,
    setGitDiffViewStyle,
    gitDiffListView,
    setGitDiffListView,
    filePanelMode,
    setFilePanelMode,
    selectedPullRequest,
    setSelectedPullRequest,
    selectedCommitSha,
    setSelectedCommitSha,
    diffSource,
    setDiffSource,
    gitStatus,
    refreshGitStatus,
    queueGitStatusRefresh,
    refreshGitDiffs,
    gitLogEntries,
    gitLogTotal,
    gitLogAhead,
    gitLogBehind,
    gitLogAheadEntries,
    gitLogBehindEntries,
    gitLogUpstream,
    gitLogLoading,
    gitLogError,
    refreshGitLog,
    gitCommitDiffs,
    shouldLoadDiffs,
    activeDiffs,
    activeDiffLoading,
    activeDiffError,
    handleSelectDiff,
    handleSelectCommit,
    handleActiveDiffPath,
    handleGitPanelModeChange,
    activeEditorFilePath,
    editorSplitCompanion,
    setEditorSplitCompanion,
    editorNavigationTarget,
    editorHighlightTarget,
    fileCompareSession,
    fileHistoryTabs,
    activeGitHistoryTabId,
    openFileTabs,
    handleOpenFile,
    handleOpenWorkspaceFileCompare,
    handleOpenScratchFileCompare,
    handleCloseFileCompare,
    handleOpenFileHistory,
    handleActivateGitHistoryTab,
    handleCloseFileHistory,
    handleCloseOtherFileHistories,
    handleCloseAllFileHistories,
    handleActivateFileTab,
    handleCloseFileTab,
    handleCloseOtherFileTabs,
    handleCloseAllFileTabs,
    handleReorderFileTabs,
    handleExitEditor,
    activeWorkspaceIdRef,
    activeWorkspaceRef,
  } = useGitPanelController({
    activeWorkspace,
    gitDiffPreloadEnabled: appSettings.preloadGitDiffs,
    isCompact,
    isTablet,
    rightPanelCollapsed,
    activeTab,
    tabletTab,
    setActiveTab,
    prDiffs: gitPullRequestDiffs,
    prDiffsLoading: gitPullRequestDiffsLoading,
    prDiffsError: gitPullRequestDiffsError,
    onOpenEditorLayoutRequest: requestEditorOpenLayout,
    onOpenGitHistoryRequest: handleOpenGitHistoryFromFileHistory,
    appMode,
  });

  useEffect(() => {
    if (!activeEditorFilePath) {
      setActiveEditorLineRange(null);
      setIsEditorFileMaximized(false);
    }
  }, [
    activeEditorFilePath,
    setActiveEditorLineRange,
    setIsEditorFileMaximized,
  ]);

  const shouldLoadGitHubPanelData = resolveShouldLoadGitHubPanelData({
    gitPanelMode,
    shouldLoadDiffs,
    diffSource,
  });

  useEffect(() => {
    resetGitHubPanelState();
  }, [activeWorkspaceId, resetGitHubPanelState]);
  const { remote: gitRemoteUrl } = useGitRemote(activeWorkspace);
  const {
    repos: gitRootCandidates,
    isLoading: gitRootScanLoading,
    error: gitRootScanError,
    depth: gitRootScanDepth,
    hasScanned: gitRootScanHasScanned,
    scan: scanGitRoots,
    setDepth: setGitRootScanDepth,
    clear: clearGitRootCandidates,
  } = useGitRepoScan(activeWorkspace);
  const {
    models,
    modelsReady,
    selectedModelId,
    setSelectedModelId,
    selectedEffort,
    setSelectedEffort,
    refreshModels,
    globalSelectionReady,
  } = useModels({
    activeWorkspace,
    onDebug: addDebugEntry,
    preferredModelId: appSettings.lastComposerModelId,
    preferredEffort: appSettings.lastComposerReasoningEffort,
    preferredSelectionReady: !appSettingsLoading,
  });

  const {
    collaborationModes,
    collaborationModesEnabled,
    selectedCollaborationMode,
    selectedCollaborationModeId,
    setSelectedCollaborationModeId,
  } = useCollaborationModes({
    activeWorkspace,
    // P1-3: no active workspace → skip collaboration catalog host work entirely.
    enabled: Boolean(activeWorkspace?.id),
    onDebug: addDebugEntry,
  });
  const {
    collaborationUiModeByThread,
    setCollaborationUiModeByThread,
    collaborationRuntimeModeByThread,
    setCollaborationRuntimeModeByThread,
    activeThreadIdForModeRef,
    lastCodexModeSyncThreadRef,
    codexComposerModeRef,
    applySelectedCollaborationMode,
    setCodexCollaborationMode,
    resolveCollaborationRuntimeMode,
    resolveCollaborationUiMode,
    handleCollaborationModeResolved,
  } = useThreadScopedCollaborationMode({
    setSelectedCollaborationModeId,
    onExplicitCollaborationModeChange: persistClaudeCollaborationMode,
  });

  const { skills } = useSkills({
    activeWorkspace,
    customSkillDirectories: appSettings.customSkillDirectories,
    onDebug: addDebugEntry,
  });
  const {
    activeEngine,
    availableEngines,
    installedEngines,
    setActiveEngine,
    engineModelsAsOptions,
    engineModelCatalogsAsOptions,
    engineStatuses,
    refreshEngineModels,
    refreshEngines,
  } = useEngineController({
    activeWorkspace,
    onDebug: addDebugEntry,
  });
  activeEngineRef.current = activeEngine;
  const {
    accessMode,
    claudeAccessModeRef,
    handleSetAccessMode,
  } = useAppShellAccessModeSection({
    activeEngine,
    appSettingsLoading,
    defaultAccessMode: appSettings.defaultAccessMode,
    persistComposerEnginePref,
  });
  const openCodeAgents = RETIRED_OPENCODE_AGENTS;
  const resolveOpenCodeAgentForThread = resolveRetiredOpenCodeSelection;
  const resolveOpenCodeVariantForThread = resolveRetiredOpenCodeSelection;

  const handleAppModeChange = useCallback(
    (mode: AppMode) => {
      setAppMode(mode);
      closeSettings();
    },
    [closeSettings],
  );
  const {
    panels: kanbanPanels,
    tasks: kanbanTasks,
    kanbanViewState,
    setKanbanViewState,
    createPanel: kanbanCreatePanel,
    updatePanel: kanbanUpdatePanel,
    deletePanel: kanbanDeletePanel,
    createTask: kanbanCreateTask,
    updateTask: kanbanUpdateTask,
    deleteTask: kanbanDeleteTask,
    reorderTask: kanbanReorderTask,
  } = useKanbanDomainHost({ workspaces, appMode });

  const {
    prompts,
    createPrompt,
    updatePrompt,
    deletePrompt,
    movePrompt,
    getWorkspacePromptsDir,
    getGlobalPromptsDir,
  } = useCustomPrompts({ activeWorkspace, onDebug: addDebugEntry });
  const { commands } = useCustomCommands({
    onDebug: addDebugEntry,
    activeEngine,
    workspaceId: activeWorkspace?.id ?? null,
  });
  const {
    initialLoadEnabled: workspaceFilesInitialLoadEnabled,
    pollingEnabled: workspaceFilesPollingEnabled,
  } = resolveWorkspaceFilesLoadFlags({
    activeWorkspaceId: activeWorkspace?.id,
    isCompact,
    rightPanelCollapsed,
    filePanelMode,
  });
  const {
    files,
    directories,
    directoryMetadata,
    sourceVersion: fileTreeSourceVersion,
    gitignoredFiles,
    gitignoredDirectories,
    isLoading: isFilesLoading,
    loadError: fileTreeLoadError,
    refreshFiles,
  } = useWorkspaceFiles({
    activeWorkspace,
    onDebug: addDebugEntry,
    initialLoadEnabled: workspaceFilesInitialLoadEnabled,
    pollingEnabled: workspaceFilesPollingEnabled,
  });
  const {
    activeGitRoot,
    alertError,
    branches,
    branchError,
    currentBranch,
    localBranches,
    remoteBranches,
    repositories,
    repositoriesLoading,
    repositoryError,
    refreshRepositories,
    selectedRepositoryRoot,
    selectRepository,
    fileStatus,
    handleApplyWorktreeChanges,
    handleCheckoutBranch,
    handleCreateBranch,
    handleUpdateBranch,
    handleUpdateAllRepositories,
    handleCheckoutAllRepositories,
    handleLoadCommonRepositoryBranches,
    handleOpenDetachedFileExplorer,
    handlePickGitRoot,
    handleRevertAllGitChanges,
    handleRevertGitFile,
    handleRevertGitPaths,
    handleSetGitRoot,
    handleStageGitAll,
    handleStageGitFile,
    handleUnstageGitAll,
    handleUnstageGitFile,
    handleUnstageGitPaths,
    worktreeApplyError,
    worktreeApplyLoading,
    worktreeApplySuccess,
  } = useAppShellGitWorkspaceOpsSection({
    activeWorkspace,
    addDebugEntry,
    clearGitRootCandidates,
    gitStatus,
    refreshGitDiffs,
    refreshGitStatus,
    t,
    updateWorkspaceSettings,
  });

  const { textareaHeight, onTextareaHeightChange } = useComposerEditorState();

  const composerEditorSettings = useComposerEditorSettings(appSettings);

  useSyncSelectedDiffPath({
    diffSource,
    centerMode,
    gitPullRequestDiffs,
    gitCommitDiffs,
    selectedDiffPath,
    setSelectedDiffPath,
  });
  const { composerSelectionResolverRef, resolveComposerSelection } =
    useComposerSelectionResolver();

  // S4 PR-D：threads controller 先整体持有，turn 级投影与 runtimeThreadBoundary
  // 由 useRuntimeThreadDomainHost 装配；根只解构其余消费方需要的字段。
  const threadsController = useThreads({
    activeWorkspace,
    onWorkspaceConnected: markWorkspaceConnected,
    onWorkspaceModelsRefresh: refreshModels,
    onDebug: addDebugEntry,
    model: null,
    effort: null,
    collaborationMode: null,
    resolveComposerSelection,
    claudeThinkingVisible,
    accessMode,
    steerEnabled: appSettings.experimentalSteerEnabled,
    customPrompts: prompts,
    activeEngine,
    useNormalizedRealtimeAdapters: appSettings.chatCanvasUseNormalizedRealtime,
    useUnifiedHistoryLoader: appSettings.chatCanvasUseUnifiedHistoryLoader,
    sessionAttributionMode: appSettings.sessionAttributionMode,
    resolveOpenCodeAgent: resolveOpenCodeAgentForThread,
    resolveOpenCodeVariant: resolveOpenCodeVariantForThread,
    resolveCollaborationUiMode,
    resolveCollaborationRuntimeMode,
    onCollaborationModeResolved: handleCollaborationModeResolved,
    runWithCreateSessionLoading,
  });
  const {
    setActiveThreadId,
    activeThreadId,
    activeItems,
    threadItemsByThread,
    historyRestoredAtMsByThread,
    approvals,
    userInputRequests,
    threadsByWorkspace,
    threadParentById,
    threadStatusById,
    historyLoadingByThreadId,
    historyLoadingProgressByThreadId,
    completionEmailIntentByThread,
    toggleCompletionEmailIntent,
    threadListLoadingByWorkspace,
    threadListPagingByWorkspace,
    threadListCursorByWorkspace,
    accountByWorkspace,
    lastAgentMessageByThread,
    interruptTurn,
    removeThread,
    removeThreads,
    pinThread,
    unpinThread,
    isThreadPinned,
    getPinTimestamp,
    pinnedThreadsVersion,
    renameThread,
    triggerAutoThreadTitle,
    isThreadAutoNaming,
    startThreadForWorkspace,
    forkThreadForWorkspace,
    forkSessionFromMessageForWorkspace,
    forkClaudeSessionFromMessageForWorkspace,
    listThreadsForWorkspace,
    loadOlderThreadsForWorkspace,
    resetWorkspaceThreads,
    refreshThread,
    sendUserMessage,
    sendUserMessageToThread,
    handleFusionStalled,
    startFork,
    startReview,
    startResume,
    startMcp,
    startSpecRoot,
    startStatus,
    startContext,
    startCompact,
    startFast,
    startMode,
    startExport,
    startImport,
    startLsp,
    startShare,
    startSharedSessionForWorkspace,
    resolveCanonicalThreadId,
    reviewPrompt,
    closeReviewPrompt,
    showPresetStep,
    choosePreset,
    highlightedPresetIndex,
    setHighlightedPresetIndex,
    highlightedBranchIndex,
    setHighlightedBranchIndex,
    highlightedCommitIndex,
    setHighlightedCommitIndex,
    handleReviewPromptKeyDown,
    confirmBranch,
    selectBranch,
    selectBranchAtIndex,
    selectCommit,
    selectCommitAtIndex,
    confirmCommit,
    updateCustomInstructions,
    confirmCustom,
    handleApprovalBatchAccept,
    handleApprovalDecision,
    handleApprovalRemember,
    handleUserInputSubmit,
    refreshAccountInfo,
    refreshAccountRateLimits,
  } = threadsController;

  const handleSelectOpenCodeAgent = ignoreRetiredOpenCodeSelection;
  const handleSelectOpenCodeVariant = ignoreRetiredOpenCodeSelection;
  const selectedOpenCodeAgent = null;
  const selectedOpenCodeVariant = null;

  useGitStatusRefreshOnTurnSettle({
    queueGitStatusRefresh,
    threadStatusById,
  });
  // S4 PR-D：turn 级会话投影 + runtimeThreadBoundary 装配下沉到 runtimeThread 域
  // host；根不再直接向 bag/投影传递 threads 全量 bags。
  const {
    activeThreadSummary,
    activeThreadEngine,
    activeThreadProviderProfileId,
    activeRateLimits,
    activeTokenUsage,
    timelinePlan,
    activePlan,
    canInterrupt,
    isProcessing,
    isReviewing,
    activeTurnId,
    hasPendingUserInput,
    runtimeThreadBoundary,
  } = useRuntimeThreadDomainHost({
    threads: threadsController,
    activeWorkspace,
    activeWorkspaceId,
    activeThreadId,
  });
  // S4 PR-C：Composer 域 host
  const {
    persistComposerSelectionForThread,
    resolveComposerSelectionForThread,
    collaborationModePayload,
    effectiveModels,
    effectiveReasoningOptions,
    effectiveReasoningSupported,
    effectiveSelectedEffort,
    effectiveSelectedModel,
    effectiveSelectedModelId,
    engineSelectedModelIdByType,
    handleSelectComposerEffort,
    handleSelectModel,
    providerModelCatalogs,
    resolvedEffort,
    resolvedModel,
    selectedAgent,
    selectedAgentRef,
    handleSelectAgent,
    reloadAgentCatalog,
    handleRefreshModelConfig,
    isModelConfigRefreshing,
    handleUserInputSubmitWithPlanApply,
    handleExitPlanModeExecute,
  } = useComposerDomainHost({
    activeThreadId,
    activeWorkspaceId,
    activeThreadEngine,
    activeThreadEngineSource:
      activeThreadSummary?.engineSource ?? activeThreadSummary?.selectedEngine,
    activeThreadProviderProfileId,
    resolveCanonicalThreadId,
    appSettingsLoading,
    addDebugEntry,
    activeEngine,
    installedEngines,
    setActiveEngine,
    appSettings,
    accessMode,
    applySelectedCollaborationMode,
    collaborationModes,
    composerInputRef,
    composerSelectionResolverRef,
    engineModelCatalogsAsOptions,
    engineModelsAsOptions,
    globalSelectionReady,
    handleSetAccessMode,
    models,
    modelsReady,
    persistComposerEnginePref,
    queueSaveSettings,
    selectedCollaborationMode,
    selectedCollaborationModeId,
    selectedEffort,
    selectedModelId,
    setAppSettings,
    setSelectedEffort,
    setSelectedModelId,
    refreshEngineModels,
    refreshModels,
    handleUserInputSubmit,
    interruptTurn,
    resolveCollaborationRuntimeMode,
    resolveCollaborationUiMode,
    sendUserMessage,
    settingsOpen,
  });
  const {
    activeAccount,
    accountSwitching,
    handleSwitchAccount,
    handleCancelSwitchAccount,
  } = useAccountSwitching({
    activeWorkspaceId,
    accountByWorkspace,
    refreshAccountInfo,
    refreshAccountRateLimits,
    alertError,
  });
  useAutoExitEmptyDiff({
    centerMode,
    autoExitEnabled: diffSource === "local",
    activeDiffCount: activeDiffs.length,
    activeDiffLoading,
    activeDiffError,
    activeThreadId,
    isCompact,
    setCenterMode,
    setSelectedDiffPath,
    setActiveTab,
  });

  const { exitDiffView, selectWorkspace, selectHome } = useWorkspaceSelection({
    workspaces,
    isCompact,
    activeWorkspaceId,
    setActiveTab,
    setActiveWorkspaceId,
    updateWorkspaceSettings,
    setCenterMode,
    setSelectedDiffPath,
  });

  useCollaborationModeThreadSync({
    activeEngine,
    activeThreadId,
    activeThreadIdForModeRef,
    appSettingsLoading,
    codexComposerModeRef,
    collaborationUiModeByThread,
    lastCodexModeSyncThreadRef,
    selectedCollaborationModeId,
    setSelectedCollaborationModeId,
  });
  const {
    closePlanPanel,
    hasActivePlan,
    isPlanMode,
    isPlanPanelDismissed,
    openPlanPanel,
    selectedKanbanTaskId,
    setSelectedKanbanTaskId,
    setWorkspaceHomeWorkspaceId,
    showGitHistory,
    showExtensions,
    showHome,
    showKanban,
    showWorkspaceHome,
  } = useAppShellViewStateSection({
    activePlan,
    activeTab,
    activeThreadId,
    activeEditorFilePath,
    activeWorkspace,
    activeWorkspaceId,
    appMode,
    expandRightPanel,
    homeOpen,
    homeWorkspaceDefaultId,
    isCompact,
    isTablet,
    selectedCollaborationMode,
    setActiveThreadId,
    setActiveWorkspaceId,
    setHomeOpen,
    tabletTab,
  });
  const {
    activeImages,
    attachImages,
    pickImages,
    removeImage,
    clearActiveImages,
    removeImagesForThread,
    activeQueue,
    activeQueuedHandoffBubble,
    handleSend,
    queueMessage,
    prefillDraft,
    setPrefillDraft,
    composerInsert,
    setComposerInsert,
    getActiveDraft,
    handleDraftChange,
    handleSendPrompt,
    handleEditQueued,
    handleDeleteQueued,
    handleFuseQueued,
    canFuseActiveQueue,
    fuseDisabledReasonKey,
    activeFusingMessageId,
    clearDraftForThread,
  } = useComposerController({
    activeThreadId,
    activeTurnId,
    activeContinuationPulse: activeThreadId
      ? (threadStatusById[activeThreadId]?.continuationPulse ?? 0)
      : 0,
    activeTerminalPulse: activeThreadId
      ? (threadStatusById[activeThreadId]?.terminalPulse ?? 0)
      : 0,
    activeWorkspaceId,
    activeWorkspace,
    isProcessing,
    isReviewing,
    isContextCompacting: activeThreadId
      ? (threadStatusById[activeThreadId]?.isContextCompacting ?? false)
      : false,
    hasPendingUserInput,
    threadStatusById,
    activeItems,
    resolveWorkspace: (workspaceId: string) =>
      workspacesById.get(workspaceId) ?? null,
    steerEnabled: appSettings.experimentalSteerEnabled,
    activeEngine,
    // 身份 id-first（fix-shared-session-identity-id-first）：
    // shared: 前缀是 hard gate，threadKind 投影仅兜底。
    isSharedSession: resolveIsSharedSession(activeThreadId, activeThreadSummary),
    resolveCanonicalThreadId,
    connectWorkspace,
    startThreadForWorkspace,
    sendUserMessage,
    sendUserMessageToThread,
    handleFusionStalled,
    startFork,
    startReview,
    startResume,
    startMcp,
    startSpecRoot,
    startStatus,
    startContext,
    startCompact,
    startFast,
    startMode,
    startExport,
    startImport,
    startLsp,
    startShare,
    setCodexCollaborationMode,
    getCodexCollaborationMode: () => {
      const threadMode = activeThreadId
        ? (collaborationUiModeByThread[activeThreadId] ?? null)
        : null;
      if (threadMode === "plan" || threadMode === "code") {
        return threadMode;
      }
      if (
        selectedCollaborationModeId === "plan" ||
        selectedCollaborationModeId === "code"
      ) {
        return selectedCollaborationModeId;
      }
      return "code";
    },
    getCodexCollaborationPayload: () => collaborationModePayload,
    interruptTurn,
  });

  // S4 PR-D：Conversation 域 host（须在 useComposerController 之后，依赖 clearDraft/removeImages）
  const {
    activeThreadIdRef,
    getThreadRows,
    handleCopyThread,
    renamePrompt,
    openRenamePrompt,
    handleRenamePromptChange,
    handleRenamePromptCancel,
    handleRenamePromptConfirm,
    deleteThreadPrompt,
    isDeleteThreadPromptBusy,
    openDeleteThreadPrompt,
    handleDeleteThreadPromptCancel,
    handleDeleteThreadPromptConfirm,
  } = useConversationDomainHost({
    runtimeThreadBoundary,
    activeThreadId,
    threadParentById,
    activeItems,
    threadsByWorkspace,
    renameThread,
    removeThread,
    clearDraftForThread,
    removeImagesForThread,
    alertError,
    deleteConversationFailedMessage: t("workspace.deleteConversationFailed"),
    addDebugEntry,
    reloadAgentCatalog,
    settingsOpen,
  });

  const handleRenameThread = useCallback(
    (workspaceId: string, threadId: string) => {
      openRenamePrompt(workspaceId, threadId);
    },
    [openRenamePrompt],
  );

  const {
    activePath,
    activeWorkspaceKanbanTasks,
    activeWorkspaceThreads,
    ensureWorkspaceThreadListLoaded,
    handleEnsureWorkspaceThreadsForSettings,
    handleInsertComposerText,
    hydratedThreadListWorkspaceIds,
    listThreadsForWorkspaceTracked,
    lockLiveSessions,
    RECENT_THREAD_LIMIT,
    recentThreads,
    scopedKanbanTasks,
    searchApiHydrationStatus,
    searchFileHydrationStatus,
    searchResults,
    sessionRadarFeed,
    workspaceActivity,
  } = useAppShellSearchRadarSection({
    activeItems,
    activeThreadId,
    activeWorkspace,
    activeWorkspaceId,
    appSettings,
    commands,
    composerInputRef,
    completionTrackerBySessionRef,
    completionTrackerReadyRef,
    directories,
    filePanelMode,
    fileTreeSourceVersion,
    files,
    getActiveDraft,
    globalSearchFilesByWorkspace,
    handleDraftChange,
    isCompact,
    isFilesLoading,
    isProcessing,
    isSearchPaletteOpen,
    kanbanTasks,
    lastAgentMessageByThread,
    listThreadsForWorkspace,
    rightPanelCollapsed,
    searchContentFilters,
    searchPaletteQuery,
    searchScope,
    setGlobalSearchFilesByWorkspace,
    skills,
    t,
    threadItemsByThread,
    threadListLoadingByWorkspace,
    threadParentById,
    threadStatusById,
    threadsByWorkspace,
    workspaces,
    workspacesById,
  });
  const {
    renameWorktreePrompt,
    renameWorktreeNotice,
    renameWorktreeUpstreamPrompt,
    confirmRenameWorktreeUpstream,
    handleOpenRenameWorktree,
    handleRenameWorktreeChange,
    handleRenameWorktreeCancel,
    handleRenameWorktreeConfirm,
    terminalTabs,
    activeTerminalId,
    onSelectTerminal,
    onNewTerminal,
    onCloseTerminal,
    terminalState,
    ensureLaunchTerminal,
    ensureTerminalWithTitle,
    restartTerminalSession,
    launchScriptState,
    runtimeRunState,
    handleToggleRuntimeConsole,
    handleToggleTerminalPanel,
    launchScriptsState,
    handleWorktreeCreated,
    resolveCloneProjectContext,
    handleSelectOpenAppId,
    handleOpenMailSession,
    handleOpenClaudeTui,
    handleSelectStatusPanelSubagent,
    openAppIconById,
    clonePrompt,
    openClonePrompt,
    confirmClonePrompt,
    cancelClonePrompt,
    updateCloneCopyName,
    chooseCloneCopiesFolder,
    useSuggestedCloneCopiesFolder,
    clearCloneCopiesFolder,
    handleArchiveActiveThread,
  } = useAppShellWorkspaceFlowsSection({
    activeThreadId,
    activeEditorFilePath,
    activeWorkspace,
    activeWorkspaceId,
    addCloneAgent,
    addDebugEntry,
    alertError,
    appSettings,
    clearDraftForThread,
    closeSettings,
    closeTerminalPanel,
    collapseRightPanel,
    connectWorkspace,
    centerMode,
    exitDiffView,
    handleToggleTerminal,
    isCompact,
    listThreadsForWorkspaceTracked,
    openTerminal,
    queueSaveSettings: (nextSettings) =>
      queueSaveSettings({
        ...appSettings,
        ...nextSettings,
      }),
    refreshThread,
    removeImagesForThread,
    removeThread,
    renameWorktree,
    renameWorktreeUpstream,
    resetWorkspaceThreads,
    selectWorkspace,
    setActiveEngine,
    setActiveTab,
    setActiveThreadId,
    setAgentTaskScrollRequest,
    setAppMode,
    setAppSettings: (updater) => {
      setAppSettings((current) => {
        const nextSettings =
          typeof updater === "function" ? updater(current) : updater;
        return {
          ...current,
          ...nextSettings,
        };
      });
    },
    setCenterMode,
    setHomeOpen,
    setSelectedKanbanTaskId,
    t,
    terminalOpen,
    threadsByWorkspace,
    updateWorkspaceSettings,
    workspaces,
  });

  const {
    worktreePrompt,
    worktreeCreateResult,
    openPrompt: openWorktreePrompt,
    confirmPrompt: confirmWorktreePrompt,
    cancelPrompt: cancelWorktreePrompt,
    closeWorktreeCreateResult,
    updateBranch: updateWorktreeBranch,
    updateBaseRef: updateWorktreeBaseRef,
    updatePublishToOrigin: updateWorktreePublishToOrigin,
    updateSetupScript: updateWorktreeSetupScript,
  } = useWorktreePrompt({
    addWorktreeAgent,
    updateWorkspaceSettings,
    connectWorkspace,
    onSelectWorkspace: selectWorkspace,
    onWorktreeCreated: handleWorktreeCreated,
    onCompactActivate: isCompact ? () => setActiveTab("codex") : undefined,
    onError: (message) => {
      addDebugEntry({
        id: `${Date.now()}-client-add-worktree-error`,
        timestamp: Date.now(),
        source: "error",
        label: "worktree/add error",
        payload: message,
      });
    },
  });

  const {
    statuses: repositoryStatuses,
    isLoading: repositoryStatusesLoading,
    isMultiRepository,
    refresh: refreshRepositoryStatuses,
  } = useMultiRepositoryGitStatus(activeWorkspace, repositories);
  const {
    handleStageRepositoryFile,
    handleUnstageRepositoryFile,
    handleUnstageRepositoryAll,
    handleUnstageRepositoryFiles,
    handleRevertRepositoryFile,
    handleRevertRepositoryFiles,
    handleStageRepositoryAll,
  } = useGitSurfaceRepositoryActionsHost({ activeWorkspace });

  const {
    commitMessage,
    commitMessageLoading,
    commitMessageError,
    commitLoading,
    pushLoading,
    syncLoading,
    commitError,
    pushError,
    syncError,
    repositoryCommitSummary,
    onCommitMessageChange: handleCommitMessageChange,
    onGenerateCommitMessage: handleGenerateCommitMessage,
    onCommit: handleCommit,
    onCommitAndPush: handleCommitAndPush,
    onCommitAndSync: handleCommitAndSync,
    onPush: handlePush,
    onSync: handleSync,
    onCommitRepositories: handleCommitRepositories,
    clearOperationErrors: clearGitOperationErrors,
  } = useGitCommitController({
    activeWorkspace,
    activeWorkspaceId,
    activeWorkspaceIdRef,
    gitStatus,
    refreshGitStatus,
    refreshGitLog,
    onMutationComplete: refreshRepositories,
    repositoryStatuses,
    refreshRepositoryStatuses,
  });

  const {
    handleSendPromptToNewAgent,
    handleCreatePrompt,
    handleUpdatePrompt,
    handleDeletePrompt,
    handleMovePrompt,
    handleRevealWorkspacePrompts,
    handleRevealGeneralPrompts,
  } = useAppShellPromptActionsSection({
    activeWorkspace,
    alertError,
    connectWorkspace,
    createPrompt,
    deletePrompt,
    getGlobalPromptsDir,
    getWorkspacePromptsDir,
    movePrompt,
    sendUserMessageToThread,
    startThreadForWorkspace,
    updatePrompt,
  });

  const {
    activeParentWorkspace,
    activeRenamePrompt,
    baseWorkspaceRef,
    isWorktreeWorkspace,
    worktreeLabel,
    worktreeRename,
  } = useAppShellWorktreeChromeSection({
    activeTab,
    activeWorkspace,
    confirmRenameWorktreeUpstream,
    handleOpenRenameWorktree,
    handleRenameWorktreeCancel,
    handleRenameWorktreeChange,
    handleRenameWorktreeConfirm,
    isPhone,
    isTablet,
    renameWorktreeNotice,
    renameWorktreePrompt,
    renameWorktreeUpstreamPrompt,
    setActiveTab,
    workspacesById,
  });

  const { isMacDesktop, isWindowsDesktop } =
    useAppShellDesktopChrome(activeWorkspace);

  useWorkspaceRestore({
    workspaces,
    hasLoaded,
    activeWorkspaceId,
    restoreThreadsOnlyOnLaunch:
      appSettings.runtimeRestoreThreadsOnlyOnLaunch !== false,
    listThreadsForWorkspace: listThreadsForWorkspaceTracked,
  });
  useWorkspaceRefreshOnFocus({
    workspaces,
    refreshWorkspaces,
    activeWorkspaceId,
    listThreadsForWorkspace: listThreadsForWorkspaceTracked,
  });

  const {
    handleAddWorkspace,
    handleOpenNewWindow,
    handleAddWorkspaceFromPath,
    handleAddAgent,
    handleAddWorktreeAgent,
    handleAddCloneAgent,
  } = useWorkspaceActions({
    activeWorkspace,
    isCompact,
    activeEngine,
    newAgentShortcut: appSettings.newAgentShortcut,
    setActiveEngine,
    addWorkspace,
    addWorkspaceFromPath,
    connectWorkspace,
    startThreadForWorkspace,
    setActiveThreadId,
    setActiveTab,
    exitDiffView,
    selectWorkspace,
    openWorktreePrompt,
    openClonePrompt,
    composerInputRef,
    showLoadingProgressDialog,
    hideLoadingProgressDialog,
    onDebug: addDebugEntry,
  });

  const {
    handleWorkspaceDragEnter,
    handleWorkspaceDragLeave,
    handleWorkspaceDragOver,
    handleWorkspaceDrop,
    isWorkspaceDropActive,
    workspaceDropTargetRef,
  } = useWorkspacePathsIntake({
    handleAddWorkspaceFromPath,
  });

  const runtimeActions = defineAppShellRuntimeActions({
    handleToggleRuntimeConsole,
    handleToggleTerminalPanel,
  });

  const agent = selectedAgent;
  const appShellDomainContexts = useAppShellDomainAssembly({
    runtimeActions,
    runtimeThreadBoundary,
    activeItems,
    activePlan,
    activeRateLimits,
    activeTokenUsage,
    activeTurnId,
    canInterrupt,
    isProcessing,
    isReviewing,
    timelinePlan,
    GitHubPanelData,
    RECENT_THREAD_LIMIT,
    SettingsView,
    accessMode,
    accountByWorkspace,
    accountSwitching,
    activeAccount,
    activeDiffError,
    activeDiffLoading,
    activeDiffs,
    activeEditorFilePath,
    activeEditorLineRange,
    activeEngine,
    activeGitRoot,
    activeImages,
    activeFusingMessageId,
    fileCompareSession,
    fileHistoryTabs,
    activeGitHistoryTabId,
    activeParentWorkspace,
    activePath,
    activeQueue,
    activeQueuedHandoffBubble,
    activeRenamePrompt,
    activeTab,
    agentTaskScrollRequest,
    activeTerminalId,
    activeThreadId,
    activeThreadIdForModeRef,
    activeThreadIdRef,
    activeWorkspace,
    activeWorkspaceId,
    activeWorkspaceIdRef,
    activeWorkspaceKanbanTasks,
    activeWorkspaceRef,
    activeWorkspaceThreads,
    addCloneAgent,
    addDebugEntry,
    addWorkspace,
    addWorkspaceFromPath,
    addWorktreeAgent,
    agent,
    alertError,
    appMode,
    appRootRef,
    appSettings,
    appSettingsLoading,
    approvals,
    assignWorkspaceGroup,
    attachImages,
    baseWorkspaceRef,
    branches,
    branchError,
    currentBranch,
    localBranches,
    remoteBranches,
    repositories,
    repositoriesLoading,
    repositoryError,
    repositoryStatuses,
    repositoryStatusesLoading,
    isMultiRepository,
    refreshRepositoryStatuses,
    handleStageRepositoryFile,
    handleUnstageRepositoryFile,
    handleUnstageRepositoryAll,
    handleUnstageRepositoryFiles,
    handleRevertRepositoryFile,
    handleRevertRepositoryFiles,
    handleStageRepositoryAll,
    handleCommitRepositories,
    repositoryCommitSummary,
    selectedRepositoryRoot,
    selectRepository,
    canFuseActiveQueue,
    fuseDisabledReasonKey,
    cancelClonePrompt,
    cancelWorktreePrompt,
    centerMode,
    chooseCloneCopiesFolder,
    choosePreset,
    claudeAccessModeRef,
    claudeThinkingVisible,
    clearCloneCopiesFolder,
    clearDebugEntries,
    clearDictationError,
    clearDictationHint,
    clearDictationTranscript,
    clearDraftForThread,
    clearGitOperationErrors,
    checkForUpdates,
    clonePrompt,
    closePlanPanel,
    closeReleaseNotes,
    closeReviewPrompt,
    closeSettings,
    closeTerminalPanel,
    closeWorktreeCreateResult,
    collapseRightPanel,
    collapseSidebar,
    commands,
    commitError,
    commitLoading,
    commitMessage,
    commitMessageError,
    commitMessageLoading,
    completionEmailIntentByThread,
    completionTrackerBySessionRef,
    completionTrackerReadyRef,
    composerEditorSettings,
    composerInputRef,
    composerInsert,
    confirmBranch,
    confirmClonePrompt,
    confirmCommit,
    confirmCustom,
    confirmRenameWorktreeUpstream,
    confirmWorktreePrompt,
    connectWorkspace,
    createPrompt,
    createWorkspaceGroup,
    debugEntries,
    debugOpen,
    debugPanelHeight,
    deletePrompt,
    deleteThreadPrompt,
    deleteWorkspaceGroup,
    deletingWorktreeIds,
    dictationError,
    dictationHint,
    dictationLevel,
    dictationModel,
    dictationReady,
    dictationState,
    dictationTranscript,
    diffScrollRequestId,
    diffSource,
    directories,
    directoryMetadata,
    dismissErrorToast,
    dismissUpdate,
    doctor,
    claudeDoctor,
    kimiDoctor,
    grokDoctor,
    opencodeDoctor,
    editorHighlightTarget,
    editorNavigationTarget,
    editorSplitCompanion,
    editorSplitLayout,
    engineModelsAsOptions,
    engineSelectedModelIdByType,
    engineStatuses,
    ensureLaunchTerminal,
    ensureTerminalWithTitle,
    ensureWorkspaceThreadListLoaded,
    errorToasts,
    exitDiffView,
    expandRightPanel,
    expandSidebar,
    filePanelMode,
    fileReferenceMode,
    fileStatus,
    fileTreeLoadError,
    fileTreeSourceVersion,
    files,
    forkThreadForWorkspace,
    forkSessionFromMessageForWorkspace,
    forkClaudeSessionFromMessageForWorkspace,
    getGlobalPromptsDir,
    getPinTimestamp,
    getThreadRows,
    getWorkspaceGroupName,
    getWorkspacePromptsDir,
    gitDiffListView,
    gitDiffViewStyle,
    gitHistoryPanelHeight,
    gitIssues,
    gitIssuesError,
    gitIssuesLoading,
    gitIssuesTotal,
    gitLogAhead,
    gitLogAheadEntries,
    gitLogBehind,
    gitLogBehindEntries,
    gitLogEntries,
    gitLogError,
    gitLogLoading,
    gitLogTotal,
    gitLogUpstream,
    gitPanelMode,
    gitPullRequestComments,
    gitPullRequestCommentsError,
    gitPullRequestCommentsLoading,
    gitPullRequestDiffs,
    gitPullRequests,
    gitPullRequestsError,
    gitPullRequestsLoading,
    gitPullRequestsTotal,
    gitRemoteUrl,
    gitRootCandidates,
    gitRootScanDepth,
    gitRootScanError,
    gitRootScanHasScanned,
    gitRootScanLoading,
    gitStatus,
    gitignoredDirectories,
    gitignoredFiles,
    globalSearchFilesByWorkspace,
    groupedWorkspaces,
    handleActivateFileTab,
    handleActiveDiffPath,
    handleAddAgent,
    handleAddCloneAgent,
    handleAddWorkspace,
    handleOpenNewWindow,
    handleAddWorktreeAgent,
    handleAppModeChange,
    handleApplyWorktreeChanges,
    handleApprovalBatchAccept,
    handleApprovalDecision,
    handleApprovalRemember,
    handleArchiveActiveThread,
    handleCancelSwitchAccount,
    handleCheckoutBranch,
    handleCloseAllFileTabs,
    handleCloseFileTab,
    handleCloseOtherFileTabs,
    handleCommit,
    handleCommitAndPush,
    handleCommitAndSync,
    handleCommitMessageChange,
    handleCopyDebug,
    handleCopyThread,
    handleCreateBranch,
    handleUpdateBranch,
    handleUpdateAllRepositories,
    handleCheckoutAllRepositories,
    handleLoadCommonRepositoryBranches,
    handleCreatePrompt,
    handleDebugClick,
    handleDeletePrompt,
    handleDeleteQueued,
    handleDeleteThreadPromptCancel,
    handleDeleteThreadPromptConfirm,
    handleDraftChange,
    handleEditQueued,
    handleEnsureWorkspaceThreadsForSettings,
    handleExitEditor,
    handleGenerateCommitMessage,
    handleGitIssuesChange,
    handleGitPanelModeChange,
    handleGitPullRequestCommentsChange,
    handleGitPullRequestDiffsChange,
    handleGitPullRequestsChange,
    handleInsertComposerText,
    handleLockPanel,
    handleMovePrompt,
    handleOpenDetachedFileExplorer,
    handleOpenFile,
    handleOpenWorkspaceFileCompare,
    handleOpenScratchFileCompare,
    handleCloseFileCompare,
    handleOpenFileHistory,
    handleActivateGitHistoryTab,
    handleCloseFileHistory,
    handleCloseOtherFileHistories,
    handleCloseAllFileHistories,
    handleOpenMailSession,
    handleOpenModelSettings,
    handleRefreshModelConfig,
    handleReorderFileTabs,
    handleResolvedClaudeThinkingVisibleChange,
    handlePickGitRoot,
    handlePush,
    handleRenamePromptCancel,
    handleRenamePromptChange,
    handleRenamePromptConfirm,
    handleRenameThread,
    handleRevealGeneralPrompts,
    handleRevealWorkspacePrompts,
    handleRevertAllGitChanges,
    handleRevertGitFile,
    handleRevertGitPaths,
    handleReviewPromptKeyDown,
    handleSelectAgent,
    handleSelectCommit,
    handleSelectDiff,
    handleSelectModel,
    handleSelectOpenAppId,
    handleSelectOpenCodeAgent,
    handleSelectOpenCodeVariant,
    handleSelectStatusPanelSubagent,
    handleSendPrompt,
    handleSendPromptToNewAgent,
    handleSetAccessMode,
    handleSetGitRoot,
    handleStageGitAll,
    handleStageGitFile,
    handleSwitchAccount,
    handleFuseQueued,
    handleSync,
    handleTestNotificationSound,
    handleToggleDictation,
    handleToggleRuntimeConsole,
    handleToggleTerminalPanel,
    handleUnlockPanel,
    handleUnstageGitAll,
    handleUnstageGitFile,
    handleUnstageGitPaths,
    handleUpdatePrompt,
    handleUserInputSubmit,
    handleUserInputSubmitWithPlanApply,
    handleExitPlanModeExecute,
    handleWorkspaceDragEnter,
    handleWorkspaceDragLeave,
    handleWorkspaceDragOver,
    handleWorkspaceDrop,
    hasActivePlan,
    highlightedBranchIndex,
    highlightedCommitIndex,
    highlightedPresetIndex,
    hydratedThreadListWorkspaceIds,
    availableEngines,
    interruptTurn,
    isCompact,
    isDeleteThreadPromptBusy,
    isEditorFileMaximized,
    isFilesLoading,
    isMacDesktop,
    isModelConfigRefreshing,
    isPanelLocked,
    isPhone,
    isPlanMode,
    isPlanPanelDismissed,
    isSearchPaletteOpen,
    isTablet,
    isThreadAutoNaming,
    isThreadPinned,
    isWindowsDesktop,
    isWorkspaceDropActive,
    isWorktreeWorkspace,
    kanbanConversationWidth,
    kanbanCreatePanel,
    kanbanCreateTask,
    kanbanDeletePanel,
    kanbanDeleteTask,
    kanbanPanels,
    kanbanReorderTask,
    kanbanTasks,
    kanbanUpdatePanel,
    kanbanUpdateTask,
    kanbanViewState,
    launchScriptState,
    launchScriptsState,
    listThreadsForWorkspaceTracked,
    liveEditPreviewEnabled,
    loadOlderThreadsForWorkspace,
    lockLiveSessions,
    models,
    moveWorkspaceGroup,
    handleOpenClaudeTui,
    normalizePath,
    onCloseTerminal,
    onDebugPanelResizeStart,
    onGitHistoryPanelResizeStart,
    onKanbanConversationResizeStart,
    onNewTerminal,
    onPlanPanelResizeStart,
    onRightPanelResizeStart,
    onSelectTerminal,
    onSidebarResizeStart,
    onTerminalPanelResizeStart,
    onTextareaHeightChange,
    openAppIconById,
    openCodeAgents,
    openDeleteThreadPrompt,
    openFileTabs,
    openPlanPanel,
    openReleaseNotes,
    openSettings,
    persistComposerSelectionForThread,
    pickImages,
    pinThread,
    pinnedThreadsVersion,
    planPanelHeight,
    prefillDraft,
    prompts,
    pushError,
    pushLoading,
    queueGitStatusRefresh,
    queueSaveSettings,
    recentThreads,
    reduceTransparency,
    windowTransparencyEnabled,
    windowOpacity,
    refreshAccountRateLimits,
    refreshEngines,
    refreshFiles,
    refreshGitDiffs,
    refreshGitLog,
    refreshThread,
    releaseNotesActiveIndex,
    releaseNotesEntries,
    releaseNotesError,
    releaseNotesLoading,
    releaseNotesOpen,
    removeImage,
    removeImagesForThread,
    removeThread,
    removeThreads,
    removeWorkspace,
    removeWorktree,
    renamePrompt,
    renameWorkspaceGroup,
    renameWorktreeUpstream,
    renameWorktreeUpstreamPrompt,
    resetGitHubPanelState,
    resetSoloSplitToHalf,
    resetWorkspaceThreads,
    resolveCloneProjectContext,
    resolveCanonicalThreadId,
    resolveComposerSelectionForThread,
    resolveOpenCodeAgentForThread,
    resolveOpenCodeVariantForThread,
    restartTerminalSession,
    retryReleaseNotesLoad,
    reviewPrompt,
    rightPanelCollapsed,
    rightPanelWidth,
    scaleShortcutText,
    scaleShortcutTitle,
    scanGitRoots,
    scopedKanbanTasks,
    searchContentFilters,
    searchApiHydrationStatus,
    searchFileHydrationStatus,
    searchPaletteQuery,
    searchPaletteSelectedIndex,
    searchResults,
    searchScope,
    selectBranch,
    selectBranchAtIndex,
    selectCommit,
    selectCommitAtIndex,
    selectHome,
    selectWorkspace,
    selectedAgent,
    selectedCommitSha,
    selectedDiffPath,
    selectedAgentRef,
    selectedKanbanTaskId,
    selectedOpenCodeAgent,
    selectedOpenCodeVariant,
    selectedPullRequest,
    sendUserMessageToThread,
    setActiveEditorLineRange,
    setActiveEngine,
    setActiveTab,
    setActiveThreadId,
    setActiveWorkspaceId,
    setAppMode,
    setAppSettings,
    setCenterMode,
    setComposerInsert,
    setDiffSource,
    setEditorSplitCompanion,
    setEditorSplitLayout,
    setFilePanelMode,
    setFileReferenceMode,
    setGitDiffListView,
    setGitDiffViewStyle,
    setGitPanelMode,
    setGitRootScanDepth,
    setHighlightedBranchIndex,
    setHighlightedCommitIndex,
    setHighlightedPresetIndex,
    setIsEditorFileMaximized,
    setIsSearchPaletteOpen,
    setKanbanViewState,
    setLiveEditPreviewEnabled,
    setPrefillDraft,
    setReduceTransparency,
    setWindowTransparencyEnabled,
    setWindowOpacity,
    setSearchContentFilters,
    setSearchPaletteQuery,
    setSearchPaletteSelectedIndex,
    setSearchScope,
    setSelectedCommitSha,
    setSelectedDiffPath,
    setSelectedKanbanTaskId,
    setSelectedPullRequest,
    setHomeOpen,
    setWorkspaceHomeWorkspaceId,
    settingsHighlightTarget,
    settingsOpen,
    settingsSection,
    loadingProgressDialog,
    dismissLoadingProgressDialog,
    shouldLoadDiffs,
    shouldLoadGitHubPanelData,
    showLoadingProgressDialog,
    hideLoadingProgressDialog,
    showDebugButton,
    showGitHistory,
    showExtensions,
    showHome,
    showKanban,
    showNextReleaseNotes,
    showPresetStep,
    showPreviousReleaseNotes,
    showWorkspaceHome,
    sidebarCollapsed,
    sidebarWidth,
    skills,
    startCompact,
    startThreadForWorkspace,
    startSharedSessionForWorkspace,
    startUpdate,
    syncError,
    syncLoading,
    t,
    tabletTab,
    terminalOpen,
    terminalPanelHeight,
    terminalState,
    terminalTabs,
    textareaHeight,
    threadItemsByThread,
    threadListCursorByWorkspace,
    threadListLoadingByWorkspace,
    threadListPagingByWorkspace,
    threadParentById,
    threadStatusById,
    historyLoadingByThreadId,
    historyLoadingProgressByThreadId,
    historyRestoredAtMsByThread,
    threadsByWorkspace,
    toggleCompletionEmailIntent,
    triggerAutoThreadTitle,
    ungroupedLabel,
    unpinThread,
    updateCloneCopyName,
    updateCustomInstructions,
    updateWorkspaceCodexBin,
    updateWorkspaceSettings,
    updateWorktreeBaseRef,
    updateWorktreeBranch,
    updateWorktreePublishToOrigin,
    updateWorktreeSetupScript,
    updaterState,
    useSuggestedCloneCopiesFolder,
    userInputRequests,
    workspaceActivity,
    workspaceDropTargetRef,
    workspaceGroups,
    homeWorkspaceSelectedId,
    workspaces,
    workspacesById,
    workspacesByPath,
    worktreeApplyError,
    worktreeApplyLoading,
    worktreeApplySuccess,
    worktreeCreateResult,
    worktreeLabel,
    worktreePrompt,
    worktreeRename,
    runtimeRunState,
    effectiveModels,
    effectiveReasoningSupported,
    effectiveSelectedModel,
    effectiveSelectedModelId,
    providerModelCatalogs,
    refreshEngineModels,
    resolvedEffort,
    resolvedModel,
    setSelectedModelId,
    applySelectedCollaborationMode,
    collaborationModePayload,
    collaborationModes,
    collaborationModesEnabled,
    collaborationRuntimeModeByThread,
    collaborationUiModeByThread,
    handleCollaborationModeResolved,
    resolveCollaborationRuntimeMode,
    resolveCollaborationUiMode,
    selectedCollaborationMode,
    selectedCollaborationModeId,
    setCodexCollaborationMode,
    setCollaborationRuntimeModeByThread,
    setCollaborationUiModeByThread,
    setSelectedCollaborationModeId,
    effectiveReasoningOptions,
    effectiveSelectedEffort,
    handleSelectComposerEffort,
    sessionRadarRunningSessions: sessionRadarFeed.runningSessions,
    sessionRadarRecentCompletedSessions:
      sessionRadarFeed.recentCompletedSessions,
    runningSessionCountByWorkspaceId:
      sessionRadarFeed.runningCountByWorkspaceId,
    recentCompletedSessionCountByWorkspaceId:
      sessionRadarFeed.recentCountByWorkspaceId,
  });

  const quickSwitcherSection = useAppShellQuickSwitcherSection({
    activeWorkspaceId,
    activityTimeline: workspaceActivity.timeline,
    expandRightPanel,
    handleOpenFile,
    handleToggleTerminalPanel,
    isCompact,
    isSearchPaletteOpen,
    openSettings,
    runningSessions: sessionRadarFeed.runningSessions,
    selectWorkspace,
    setActiveTab,
    setActiveThreadId,
    setAppMode,
    setCenterMode,
    setFilePanelMode,
    setGitPanelMode,
    setHomeOpen,
    setIsSearchPaletteOpen,
    setWorkspaceHomeWorkspaceId,
    threadsByWorkspace,
    workspaces,
  });

  // T2.1–T2.3 zone provider values
  const runtimeThreadProviderValue = useMemoizedRuntimeThreadProviderValue({
    activeItems,
    activePlan,
    activeRateLimits,
    activeTokenUsage,
    activeTurnId,
    canInterrupt,
    isProcessing,
    isReviewing,
    timelinePlan,
    interruptTurn,
    runtimeThreadBoundary,
  });
  const composerProviderValue = useMemoizedComposerProviderValue({
    handleSend,
    handleDraftChange,
    getActiveDraft,
    queueMessage,
    clearActiveImages,
    activeImages,
    composerInsert,
    setComposerInsert,
    prefillDraft,
    setPrefillDraft,
    interruptTurn,
    canInterrupt,
  });
  const layoutChromeProviderValue = useMemoizedLayoutChromeProviderValue({
    appMode,
    centerMode,
    activeTab,
    accessMode,
    filePanelMode,
    gitPanelMode,
    sidebarCollapsed,
    sidebarWidth,
    rightPanelCollapsed,
    rightPanelWidth,
    isPanelLocked,
    expandSidebar,
    collapseSidebar,
    expandRightPanel,
    collapseRightPanel,
    setAppMode,
    setCenterMode,
    setActiveTab,
    setFilePanelMode,
    setGitPanelMode,
  });

  // T2.4：search/composer 分组入参（在 Providers 下的 AppShellView 内消费）
  const searchAndComposerInput = {
    identity: {
      activeWorkspace,
      activeWorkspaceId,
      workspacesById,
      workspacesByPath,
      appSettings,
      isCompact,
    },
    send: {
      activeWorkspace,
      clearActiveImages,
      connectWorkspace,
      gitPullRequestDiffs,
      handleSend,
      queueMessage,
      selectedPullRequest,
      sendUserMessageToThread,
      startThreadForWorkspace,
      canInterrupt,
      interruptTurn,
      getActiveDraft,
      handleDraftChange,
      handleAddAgent,
    },
    navigation: {
      filePanelMode,
      gitPanelMode,
      setCenterMode,
      setGitPanelMode,
      setPrefillDraft,
      centerMode,
      selectWorkspace,
      setActiveTab,
      setActiveThreadId,
      setAppMode,
      setDiffSource,
      exitDiffView,
      handleOpenFile,
      setKanbanViewState,
      setSelectedKanbanTaskId,
    },
    search: {
      isSearchPaletteOpen,
      searchPaletteQuery,
      searchContentFilters,
      searchResults,
      searchScope,
      setIsSearchPaletteOpen,
      setSearchContentFilters,
      setSearchPaletteQuery,
      setSearchPaletteSelectedIndex,
      setSearchScope,
      setSelectedCommitSha,
      setSelectedDiffPath,
      setSelectedPullRequest,
      activeEditorFilePath,
    },
    chrome: {
      closeQuickSwitcher: quickSwitcherSection.closeQuickSwitcher,
      handleOpenQuickSwitcher: quickSwitcherSection.handleOpenQuickSwitcher,
      handleQuickSwitcherNavigate:
        quickSwitcherSection.handleQuickSwitcherNavigate,
      handleQuickSwitcherSelectFile:
        quickSwitcherSection.handleQuickSwitcherSelectFile,
      handleQuickSwitcherSelectSession:
        quickSwitcherSection.handleQuickSwitcherSelectSession,
      isQuickSwitcherOpen: quickSwitcherSection.isQuickSwitcherOpen,
      quickSwitcherRecentFileGroups:
        quickSwitcherSection.quickSwitcherRecentFileGroups,
      quickSwitcherRunningSessions:
        quickSwitcherSection.quickSwitcherRunningSessions,
      quickSwitcherSessionGroups:
        quickSwitcherSection.quickSwitcherSessionGroups,
      increaseUiScale,
      decreaseUiScale,
      resetUiScale,
      kanbanTasks,
    },
  };


  return {
    runtimeThreadProviderValue,
    composerProviderValue,
    layoutChromeProviderValue,
    appShellDomainContexts,
    searchAndComposerInput,
  };
}
