// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "कनेक्शन विफल",
    "requestFailed": "अनुरोध विफल",
    "unexpectedError": "एक अप्रत्याशित त्रुटि हुई",
    "sessionExpired": "सत्र समाप्त हो गया",
    "rateLimited": "दर सीमित। कृपया बाद में पुनः प्रयास करें।",
    "networkError": "नेटवर्क त्रुटि। कृपया अपना कनेक्शन जाँचें।",
    "failedToAddWorkspace": "वर्कस्पेस जोड़ने में विफल।",
    "failedToOpenNewWindow": "नई विंडो खोलने में विफल।",
    "failedToCreateSession": "सत्र बनाने में विफल।",
    "failedToCreateSessionNoThreadId": "रनटाइम ने कोई नई सत्र आईडी नहीं लौटाई।",
    "failedToCreateSessionRuntimeRecovering": "इस सत्र को बनाते समय रनटाइम पुनः आरंभ हो रहा था। ऐप पहले ही एक बार पुनः प्रयास कर चुका है। वर्कस्पेस को पुनः कनेक्ट करें और फिर प्रयास करें।",
    "codexProviderWireApiUnsupported": "वर्तमान Codex CLI wire_api = \"chat\" का समर्थन नहीं करता। यदि यह provider Responses API का समर्थन करता है, तो wire_api = \"responses\" का उपयोग करें। यदि यह केवल Chat Completions का समर्थन करता है, तो पहले protocol conversion service या router कॉन्फ़िगर करें।",
    "codexProviderConfigInvalid": "इस Codex provider का configuration मान्य TOML नहीं है। Syntax जाँचें और smart quotes के बजाय सीधे English half-width quotes (\") का उपयोग करें।",
    "reconnectAndRetryCreateSession": "पुनः कनेक्ट करें और निर्माण पुनः प्रयास करें",
    "reconnectingAndRetryingCreateSession": "पुनः कनेक्ट और निर्माण पुनः प्रयास हो रहा है...",
    "runtimeRecovered": "रनटाइम पुनर्प्राप्त हुआ।",
    "retryingCreateSessionAfterRecovery": "सत्र निर्माण पुनः प्रयास हो रहा है...",
    "cliNotFound": "न तो Claude Code CLI और न ही Codex CLI मिला। कृपया इनमें से एक इंस्टॉल करें।",
    "cliNotFoundHint": "Claude Code इंस्टॉल करें: curl -fsSL https://claude.ai/install.sh | bash\nCodex इंस्टॉल करें: npm install -g @openai/codex",
    "codexCliNotFound": "Codex CLI नहीं मिला। Codex इंस्टॉल करें और सुनिश्चित करें कि `codex` आपके PATH पर है।",
    "couldntOpenWorkspace": "वर्कस्पेस नहीं खुल सका",
    "dismissError": "त्रुटि खारिज करें",
    "applicationErrorTitle": "Application Error",
    "applicationErrorDescription": "An unexpected error stopped the UI. Copy the diagnostic report below, send it to the developers, then reload the app.",
    "applicationErrorReload": "Reload",
    "applicationErrorCopyReport": "Copy error report",
    "applicationErrorCopyDone": "Error report copied. Paste it into your feedback.",
    "applicationErrorCopyDownloaded": "Clipboard unavailable. A report file was downloaded instead — attach it when you report the issue.",
    "applicationErrorCopyFailed": "Could not copy or download the report. Select the text below and copy it manually.",
    "applicationErrorDetails": "Error details",
    "applicationErrorFeedbackTitle": "How to report this to developers",
    "applicationErrorFeedbackStep1": "Click “Copy error report”.",
    "applicationErrorFeedbackStep2": "Open the feedback page and create a new issue, then paste the report.",
    "applicationErrorFeedbackStep3": "Add what you were doing (cold start / streaming / switching workspace, etc.) and whether Reload recovers it.",
    "applicationErrorOpenFeedback": "Open feedback page",
    "applicationErrorMeta": "version: {{version}} · class: {{errorClass}} · platform: {{platform}}",
    "applicationErrorMessageLabel": "Error message",
    "applicationErrorDecodedLabel": "Decoded React #{{code}}",
    "applicationErrorComponentStackLabel": "Component stack",
    "applicationErrorStackLabel": "JavaScript stack"
  }
};

export default errors;
