// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "Не удалось подключиться",
    "requestFailed": "Запрос не выполнен",
    "unexpectedError": "Произошла непредвиденная ошибка",
    "sessionExpired": "Сессия истекла",
    "rateLimited": "Превышен лимит запросов. Повторите попытку позже.",
    "networkError": "Ошибка сети. Проверьте подключение.",
    "failedToAddWorkspace": "Не удалось добавить рабочую область.",
    "failedToOpenNewWindow": "Не удалось открыть новое окно.",
    "failedToCreateSession": "Не удалось создать сессию.",
    "failedToCreateSessionNoThreadId": "Среда выполнения не вернула идентификатор новой сессии.",
    "failedToCreateSessionRuntimeRecovering": "Среда выполнения перезапускалась во время создания этой сессии. Приложение уже повторило попытку один раз. Переподключите рабочую область и попробуйте снова.",
    "codexProviderWireApiUnsupported": "Текущая версия Codex CLI не поддерживает wire_api = \"chat\". Если поставщик поддерживает Responses API, используйте wire_api = \"responses\". Если поддерживается только Chat Completions, сначала настройте сервис преобразования протокола или router.",
    "codexProviderConfigInvalid": "Конфигурация этого поставщика Codex не является допустимым TOML. Проверьте синтаксис и используйте прямые английские кавычки (\") вместо типографских.",
    "reconnectAndRetryCreateSession": "Переподключиться и повторить создание",
    "reconnectingAndRetryingCreateSession": "Переподключение и повтор создания...",
    "runtimeRecovered": "Среда выполнения восстановлена.",
    "retryingCreateSessionAfterRecovery": "Повтор создания сессии...",
    "cliNotFound": "Не найдены ни Claude Code CLI, ни Codex CLI. Установите один из них.",
    "cliNotFoundHint": "Установите Claude Code: curl -fsSL https://claude.ai/install.sh | bash\nУстановите Codex: npm install -g @openai/codex",
    "codexCliNotFound": "Codex CLI не найден. Установите Codex и убедитесь, что `codex` доступен в вашем PATH.",
    "couldntOpenWorkspace": "Не удалось открыть рабочую область",
    "dismissError": "Скрыть ошибку",
    "applicationErrorTitle": "Application Error",
    "applicationErrorDescription": "An unexpected error stopped the UI. Copy the diagnostic report below, send it to the developers, then reload the app.",
    "applicationErrorReload": "Reload",
    "applicationErrorCopyReport": "Copy error report",
    "applicationErrorCopyDone": "Error report copied. Paste it into your feedback.",
    "applicationErrorCopyDownloaded": "Clipboard unavailable. A report file was downloaded instead — attach it when you report the issue.",
    "applicationErrorCopyFailed": "Could not copy or download the report. Select the text below and copy it manually.",
    "applicationErrorDetails": "Error details",
    "applicationErrorFeedbackTitle": "How to report this to developers",
    "applicationErrorFeedbackStep1": "Click “Copy error report”.",
    "applicationErrorFeedbackStep2": "Open the feedback page and create a new issue, then paste the report.",
    "applicationErrorFeedbackStep3": "Add what you were doing (cold start / streaming / switching workspace, etc.) and whether Reload recovers it.",
    "applicationErrorOpenFeedback": "Open feedback page",
    "applicationErrorMeta": "version: {{version}} · class: {{errorClass}} · platform: {{platform}}",
    "applicationErrorMessageLabel": "Error message",
    "applicationErrorDecodedLabel": "Decoded React #{{code}}",
    "applicationErrorComponentStackLabel": "Component stack",
    "applicationErrorStackLabel": "JavaScript stack"
  }
};

export default errors;
