// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "연결 실패",
    "requestFailed": "요청 실패",
    "unexpectedError": "예기치 않은 오류가 발생했습니다",
    "sessionExpired": "세션이 만료되었습니다",
    "rateLimited": "요청 한도를 초과했습니다. 나중에 다시 시도하세요.",
    "networkError": "네트워크 오류. 연결을 확인하세요.",
    "failedToAddWorkspace": "작업 공간을 추가하지 못했습니다.",
    "failedToOpenNewWindow": "새 창을 열지 못했습니다.",
    "failedToCreateSession": "세션을 생성하지 못했습니다.",
    "failedToCreateSessionNoThreadId": "런타임이 새 세션 id를 반환하지 않았습니다.",
    "failedToCreateSessionRuntimeRecovering": "이 세션을 생성하는 동안 런타임이 재시작 중이었습니다. 앱이 이미 한 번 재시도했습니다. 작업 공간을 재연결하고 다시 시도하세요.",
    "codexProviderWireApiUnsupported": "현재 Codex CLI는 wire_api = \"chat\"을 지원하지 않습니다. 이 공급자가 Responses API를 지원하면 wire_api = \"responses\"를 사용하세요. Chat Completions만 지원하면 먼저 프로토콜 변환 서비스 또는 router를 구성하세요.",
    "codexProviderConfigInvalid": "이 Codex 공급자 설정은 유효한 TOML이 아닙니다. 구문을 확인하고 스마트 따옴표 대신 영문 반각 직선 따옴표(\")를 사용하세요.",
    "reconnectAndRetryCreateSession": "재연결 후 생성 재시도",
    "reconnectingAndRetryingCreateSession": "재연결하여 생성을 재시도하는 중...",
    "runtimeRecovered": "런타임이 복구되었습니다.",
    "retryingCreateSessionAfterRecovery": "세션 생성을 재시도하는 중...",
    "cliNotFound": "Claude Code CLI와 Codex CLI를 모두 찾을 수 없습니다. 둘 중 하나를 설치하세요.",
    "cliNotFoundHint": "Claude Code 설치: curl -fsSL https://claude.ai/install.sh | bash\nCodex 설치: npm install -g @openai/codex",
    "codexCliNotFound": "Codex CLI를 찾을 수 없습니다. Codex를 설치하고 `codex`가 PATH에 있는지 확인하세요.",
    "couldntOpenWorkspace": "작업 공간을 열 수 없습니다",
    "dismissError": "오류 닫기",
    "applicationErrorTitle": "Application Error",
    "applicationErrorDescription": "An unexpected error stopped the UI. Copy the diagnostic report below, send it to the developers, then reload the app.",
    "applicationErrorReload": "Reload",
    "applicationErrorCopyReport": "Copy error report",
    "applicationErrorCopyDone": "Error report copied. Paste it into your feedback.",
    "applicationErrorCopyDownloaded": "Clipboard unavailable. A report file was downloaded instead — attach it when you report the issue.",
    "applicationErrorCopyFailed": "Could not copy or download the report. Select the text below and copy it manually.",
    "applicationErrorDetails": "Error details",
    "applicationErrorFeedbackTitle": "How to report this to developers",
    "applicationErrorFeedbackStep1": "Click “Copy error report”.",
    "applicationErrorFeedbackStep2": "Open the feedback page and create a new issue, then paste the report.",
    "applicationErrorFeedbackStep3": "Add what you were doing (cold start / streaming / switching workspace, etc.) and whether Reload recovers it.",
    "applicationErrorOpenFeedback": "Open feedback page",
    "applicationErrorMeta": "version: {{version}} · class: {{errorClass}} · platform: {{platform}}",
    "applicationErrorMessageLabel": "Error message",
    "applicationErrorDecodedLabel": "Decoded React #{{code}}",
    "applicationErrorComponentStackLabel": "Component stack",
    "applicationErrorStackLabel": "JavaScript stack"
  }
};

export default errors;
